export type NutritionGoal = 'lose' | 'maintain' | 'gain';
export type MealType = 'breakfast' | 'lunch' | 'dinner' | 'snack' | 'post-workout';
export type DietType = 'balanced' | 'vegetarian' | 'vegan' | 'lactose-free';
export type PrepTime = 'quick' | 'standard' | 'meal-prep';
export type BudgetType = 'low' | 'medium' | 'flexible';
export type AssistantStep = 'goal' | 'meal' | 'diet' | 'time' | 'budget' | 'result';

export interface AssistantAnswers {
  goal: NutritionGoal;
  meal: MealType;
  diet: DietType;
  time: PrepTime;
  budget: BudgetType;
}

export interface AssistantOption {
  value: string;
  label: string;
  description: string;
  icon: string;
}

export interface MealRecommendation {
  title: string;
  subtitle: string;
  calories: number;
  protein: number;
  carbs: number;
  fats: number;
  prepMinutes: number;
  cost: string;
  ingredients: string[];
  steps: string[];
  swaps: string[];
  coachTip: string;
}

interface MealTemplate extends MealRecommendation {
  meals: MealType[];
  diets: DietType[];
  times: PrepTime[];
  budgets: BudgetType[];
}

export const ASSISTANT_OPTIONS: Record<Exclude<AssistantStep, 'result'>, AssistantOption[]> = {
  goal: [
    { value: 'lose', label: 'Fat loss', description: 'High volume, filling meals and controlled calories.', icon: '↘' },
    { value: 'maintain', label: 'Maintain', description: 'Balanced portions for energy and recovery.', icon: '◎' },
    { value: 'gain', label: 'Build muscle', description: 'More calories, protein and training fuel.', icon: '↗' },
  ],
  meal: [
    { value: 'breakfast', label: 'Breakfast', description: 'Start the day with steady energy.', icon: '☀' },
    { value: 'lunch', label: 'Lunch', description: 'A complete meal for the middle of the day.', icon: '◐' },
    { value: 'dinner', label: 'Dinner', description: 'Recovery-focused and easy to digest.', icon: '☾' },
    { value: 'snack', label: 'Snack', description: 'Small, practical and protein-aware.', icon: '◇' },
    { value: 'post-workout', label: 'Post-workout', description: 'Protein and carbohydrates for recovery.', icon: '⚡' },
  ],
  diet: [
    { value: 'balanced', label: 'No restrictions', description: 'Uses a wide range of foods.', icon: '✓' },
    { value: 'vegetarian', label: 'Vegetarian', description: 'No meat or fish.', icon: '◉' },
    { value: 'vegan', label: 'Vegan', description: 'Only plant-based ingredients.', icon: '⌁' },
    { value: 'lactose-free', label: 'Lactose-free', description: 'No regular dairy products.', icon: '○' },
  ],
  time: [
    { value: 'quick', label: 'Under 10 min', description: 'Minimal cooking and cleanup.', icon: '10' },
    { value: 'standard', label: '10–30 min', description: 'A normal freshly cooked meal.', icon: '25' },
    { value: 'meal-prep', label: 'Meal prep', description: 'Cook several portions at once.', icon: '×4' },
  ],
  budget: [
    { value: 'low', label: 'Budget friendly', description: 'Simple and affordable staples.', icon: '$' },
    { value: 'medium', label: 'Balanced budget', description: 'Good variety without overspending.', icon: '$$' },
    { value: 'flexible', label: 'Flexible', description: 'Prioritizes taste and nutrition.', icon: '$$$' },
  ],
};

const MEALS: MealTemplate[] = [
  {
    title: 'Protein overnight oats',
    subtitle: 'Creamy oats with berries, seeds and a high-protein base.',
    meals: ['breakfast', 'snack'],
    diets: ['balanced', 'vegetarian'],
    times: ['quick', 'meal-prep'],
    budgets: ['low', 'medium'],
    calories: 455,
    protein: 35,
    carbs: 57,
    fats: 11,
    prepMinutes: 7,
    cost: 'Low',
    ingredients: ['60 g oats', '200 g Greek yogurt', '100 ml milk', '100 g berries', '10 g chia seeds', 'Cinnamon'],
    steps: ['Mix oats, yogurt, milk and chia.', 'Refrigerate overnight or at least 2 hours.', 'Add berries and cinnamon before eating.'],
    swaps: ['Use soy yogurt and soy milk for a vegan version.', 'Replace berries with banana for more carbohydrates.'],
    coachTip: 'Prepare three jars at once to make breakfast automatic on busy training days.',
  },
  {
    title: 'Egg and avocado breakfast wrap',
    subtitle: 'A warm, filling wrap with protein, fiber and healthy fats.',
    meals: ['breakfast', 'post-workout'],
    diets: ['balanced', 'vegetarian', 'lactose-free'],
    times: ['quick', 'standard'],
    budgets: ['low', 'medium'],
    calories: 520,
    protein: 31,
    carbs: 48,
    fats: 23,
    prepMinutes: 10,
    cost: 'Low',
    ingredients: ['3 eggs', '1 whole-wheat wrap', '½ avocado', 'Tomato', 'Spinach', 'Salt and pepper'],
    steps: ['Scramble the eggs with spinach.', 'Warm the wrap.', 'Add eggs, avocado and tomato, then roll tightly.'],
    swaps: ['Use egg whites for fewer calories.', 'Add salsa or hot sauce without significantly increasing calories.'],
    coachTip: 'For fat loss, use 2 eggs and extra vegetables. For muscle gain, add a second wrap.',
  },
  {
    title: 'Tofu berry smoothie bowl',
    subtitle: 'A thick plant-based bowl with fruit and complete soy protein.',
    meals: ['breakfast', 'snack', 'post-workout'],
    diets: ['vegan', 'lactose-free'],
    times: ['quick'],
    budgets: ['medium', 'flexible'],
    calories: 430,
    protein: 28,
    carbs: 61,
    fats: 10,
    prepMinutes: 6,
    cost: 'Medium',
    ingredients: ['180 g silken tofu', '1 frozen banana', '150 g frozen berries', '150 ml soy milk', '20 g oats', '10 g peanut butter'],
    steps: ['Blend tofu, fruit, soy milk and oats until thick.', 'Pour into a bowl.', 'Top with peanut butter and a few berries.'],
    swaps: ['Use mango instead of berries.', 'Add vegan protein powder to increase protein by 20–25 g.'],
    coachTip: 'Soy milk and tofu provide more protein than most other plant-based alternatives.',
  },
  {
    title: 'Chicken rice power bowl',
    subtitle: 'A reliable high-protein bowl for performance and recovery.',
    meals: ['lunch', 'dinner', 'post-workout'],
    diets: ['balanced', 'lactose-free'],
    times: ['standard', 'meal-prep'],
    budgets: ['low', 'medium'],
    calories: 650,
    protein: 52,
    carbs: 78,
    fats: 14,
    prepMinutes: 25,
    cost: 'Medium',
    ingredients: ['170 g chicken breast', '200 g cooked rice', '150 g mixed vegetables', '1 tsp olive oil', 'Soy sauce', 'Garlic and paprika'],
    steps: ['Season and cook the chicken.', 'Sauté or steam the vegetables.', 'Serve over rice and finish with soy sauce.'],
    swaps: ['Replace chicken with turkey.', 'Use cauliflower rice for a lower-calorie version.'],
    coachTip: 'Cook four portions and store the sauce separately so the rice keeps its texture.',
  },
  {
    title: 'Salmon potato recovery plate',
    subtitle: 'Omega-3 fats, lean protein and easy-to-digest carbohydrates.',
    meals: ['lunch', 'dinner', 'post-workout'],
    diets: ['balanced', 'lactose-free'],
    times: ['standard'],
    budgets: ['medium', 'flexible'],
    calories: 690,
    protein: 46,
    carbs: 63,
    fats: 27,
    prepMinutes: 28,
    cost: 'High',
    ingredients: ['170 g salmon', '300 g potatoes', 'Green beans', '1 tsp olive oil', 'Lemon', 'Dill and garlic'],
    steps: ['Roast or air-fry the potatoes.', 'Season and cook the salmon.', 'Steam the beans and serve with lemon.'],
    swaps: ['Use canned tuna for a cheaper option.', 'Replace potatoes with rice after intense training.'],
    coachTip: 'This is especially useful after demanding sessions because it combines protein, carbs and omega-3 fats.',
  },
  {
    title: 'Turkey hummus crunch wrap',
    subtitle: 'Fast, portable and balanced for lunch or a substantial snack.',
    meals: ['lunch', 'snack'],
    diets: ['balanced', 'lactose-free'],
    times: ['quick'],
    budgets: ['low', 'medium'],
    calories: 480,
    protein: 38,
    carbs: 51,
    fats: 14,
    prepMinutes: 8,
    cost: 'Low',
    ingredients: ['1 whole-wheat wrap', '120 g sliced turkey', '40 g hummus', 'Lettuce', 'Cucumber', 'Bell pepper'],
    steps: ['Spread hummus over the wrap.', 'Layer turkey and vegetables.', 'Roll tightly and slice in half.'],
    swaps: ['Use cooked chicken leftovers.', 'Add a second wrap for a higher-calorie meal.'],
    coachTip: 'Keep washed vegetables ready in the fridge to make this meal in under five minutes.',
  },
  {
    title: 'Lentil quinoa meal-prep bowl',
    subtitle: 'Plant-based protein, fiber and slow-release carbohydrates.',
    meals: ['lunch', 'dinner'],
    diets: ['vegetarian', 'vegan', 'lactose-free'],
    times: ['standard', 'meal-prep'],
    budgets: ['low', 'medium'],
    calories: 570,
    protein: 29,
    carbs: 85,
    fats: 13,
    prepMinutes: 30,
    cost: 'Low',
    ingredients: ['180 g cooked lentils', '150 g cooked quinoa', 'Roasted peppers', 'Spinach', '1 tbsp tahini', 'Lemon and cumin'],
    steps: ['Cook quinoa and warm the lentils.', 'Roast or sauté the vegetables.', 'Mix tahini with lemon and water, then assemble.'],
    swaps: ['Use brown rice instead of quinoa.', 'Add tofu or edamame for more protein.'],
    coachTip: 'Legumes and grains complement each other and create a stronger amino-acid profile.',
  },
  {
    title: 'Creamy high-protein pasta',
    subtitle: 'Comforting pasta with a lighter protein-rich sauce.',
    meals: ['lunch', 'dinner', 'post-workout'],
    diets: ['balanced', 'vegetarian'],
    times: ['standard', 'meal-prep'],
    budgets: ['low', 'medium'],
    calories: 720,
    protein: 48,
    carbs: 98,
    fats: 16,
    prepMinutes: 22,
    cost: 'Medium',
    ingredients: ['100 g dry pasta', '180 g cottage cheese', 'Tomato sauce', 'Spinach', '15 g parmesan', 'Garlic and basil'],
    steps: ['Cook the pasta and reserve a little water.', 'Blend cottage cheese with tomato sauce.', 'Warm the sauce, add spinach and combine with pasta.'],
    swaps: ['Use lentil pasta for more protein.', 'Use lactose-free cottage cheese if needed.'],
    coachTip: 'This is a strong post-workout choice when you need both protein and a larger carbohydrate serving.',
  },
  {
    title: 'Chickpea vegetable curry',
    subtitle: 'A warming plant-based dinner built from affordable pantry foods.',
    meals: ['lunch', 'dinner'],
    diets: ['vegetarian', 'vegan', 'lactose-free'],
    times: ['standard', 'meal-prep'],
    budgets: ['low'],
    calories: 590,
    protein: 23,
    carbs: 91,
    fats: 15,
    prepMinutes: 27,
    cost: 'Low',
    ingredients: ['200 g chickpeas', '150 g cooked rice', 'Tomato', 'Light coconut milk', 'Mixed vegetables', 'Curry powder'],
    steps: ['Cook vegetables with curry powder.', 'Add tomato, coconut milk and chickpeas.', 'Simmer for 12 minutes and serve with rice.'],
    swaps: ['Add tofu for more protein.', 'Use less rice and more vegetables for fat loss.'],
    coachTip: 'Freeze individual portions so you always have a balanced meal available.',
  },
  {
    title: 'Greek yogurt protein cup',
    subtitle: 'A no-cook snack with protein, fruit and a little crunch.',
    meals: ['snack', 'breakfast'],
    diets: ['balanced', 'vegetarian'],
    times: ['quick'],
    budgets: ['low', 'medium'],
    calories: 330,
    protein: 30,
    carbs: 37,
    fats: 8,
    prepMinutes: 3,
    cost: 'Low',
    ingredients: ['250 g Greek yogurt', '1 small banana', '15 g walnuts', 'Cinnamon', '1 tsp honey'],
    steps: ['Add yogurt to a bowl.', 'Top with sliced banana, walnuts and cinnamon.', 'Add honey if desired.'],
    swaps: ['Use lactose-free yogurt.', 'Replace walnuts with cereal for more carbohydrates.'],
    coachTip: 'This snack works well one to two hours before training because it is easy to digest.',
  },
  {
    title: 'Tuna and bean protein salad',
    subtitle: 'High protein, high fiber and ready in minutes.',
    meals: ['lunch', 'dinner', 'snack'],
    diets: ['balanced', 'lactose-free'],
    times: ['quick'],
    budgets: ['low'],
    calories: 470,
    protein: 44,
    carbs: 42,
    fats: 13,
    prepMinutes: 7,
    cost: 'Low',
    ingredients: ['1 can tuna', '150 g white beans', 'Tomato', 'Cucumber', 'Red onion', 'Lemon and 1 tsp olive oil'],
    steps: ['Drain the tuna and beans.', 'Chop the vegetables.', 'Mix everything with lemon, oil, salt and pepper.'],
    swaps: ['Use chickpeas and tofu for a plant-based version.', 'Serve with bread after training.'],
    coachTip: 'Rinsing canned beans lowers sodium and improves their texture.',
  },
  {
    title: 'Peanut banana recovery shake',
    subtitle: 'Fast carbohydrates and protein when a full meal is not practical.',
    meals: ['post-workout', 'snack', 'breakfast'],
    diets: ['balanced', 'vegetarian', 'lactose-free', 'vegan'],
    times: ['quick'],
    budgets: ['low', 'medium', 'flexible'],
    calories: 510,
    protein: 34,
    carbs: 68,
    fats: 14,
    prepMinutes: 4,
    cost: 'Low',
    ingredients: ['1 banana', '300 ml soy milk', '30 g protein powder', '20 g peanut butter', '30 g oats', 'Ice and cinnamon'],
    steps: ['Add all ingredients to a blender.', 'Blend until smooth.', 'Drink immediately after training or alongside a lighter meal.'],
    swaps: ['Use berries for fewer carbohydrates.', 'Add another banana for muscle gain.'],
    coachTip: 'Choose a plant or whey protein that provides around 20–25 g protein per serving.',
  },
  {
    title: 'Apple cinnamon skyr oats',
    subtitle: 'A crisp, creamy breakfast with slow carbohydrates and plenty of protein.',
    meals: ['breakfast', 'snack'],
    diets: ['balanced', 'vegetarian'],
    times: ['quick', 'meal-prep'],
    budgets: ['low', 'medium'],
    calories: 420,
    protein: 34,
    carbs: 55,
    fats: 7,
    prepMinutes: 6,
    cost: 'Low',
    ingredients: ['250 g skyr', '50 g oats', '1 apple', 'Cinnamon', '10 g pumpkin seeds', '1 tsp honey'],
    steps: ['Dice the apple.', 'Mix skyr, oats and cinnamon.', 'Top with apple, seeds and honey.'],
    swaps: ['Use lactose-free skyr.', 'Microwave the apple with cinnamon for a warm version.'],
    coachTip: 'The combination of protein and fiber helps keep hunger controlled through the morning.',
  },
  {
    title: 'Banana protein pancakes',
    subtitle: 'Soft three-ingredient pancakes that work for breakfast or recovery.',
    meals: ['breakfast', 'post-workout'],
    diets: ['balanced', 'vegetarian', 'lactose-free'],
    times: ['quick', 'standard'],
    budgets: ['low'],
    calories: 495,
    protein: 36,
    carbs: 62,
    fats: 12,
    prepMinutes: 10,
    cost: 'Low',
    ingredients: ['1 banana', '2 eggs', '40 g oats', '25 g protein powder', 'Cinnamon', '100 g berries'],
    steps: ['Blend banana, eggs, oats and protein powder.', 'Cook small pancakes in a non-stick pan.', 'Serve with berries and cinnamon.'],
    swaps: ['Use soy protein and a flax egg for a plant-based version.', 'Add yogurt for an extra creamy topping.'],
    coachTip: 'Small pancakes flip more easily and cook evenly without much oil.',
  },
  {
    title: 'Savory cottage cheese toast',
    subtitle: 'Crunchy toast topped with creamy protein and fresh vegetables.',
    meals: ['breakfast', 'snack', 'lunch'],
    diets: ['balanced', 'vegetarian'],
    times: ['quick'],
    budgets: ['low', 'medium'],
    calories: 390,
    protein: 31,
    carbs: 43,
    fats: 11,
    prepMinutes: 5,
    cost: 'Low',
    ingredients: ['2 slices whole-grain bread', '180 g cottage cheese', 'Tomato', 'Cucumber', 'Black pepper', 'Fresh herbs'],
    steps: ['Toast the bread.', 'Season the cottage cheese.', 'Top the toast with cottage cheese and vegetables.'],
    swaps: ['Use lactose-free cottage cheese.', 'Add smoked salmon for more protein and omega-3 fats.'],
    coachTip: 'Choose bread with at least 5 g fiber per 100 g for better fullness.',
  },
  {
    title: 'Mediterranean tofu scramble',
    subtitle: 'A colorful plant-based breakfast with vegetables and high-protein tofu.',
    meals: ['breakfast', 'lunch'],
    diets: ['vegetarian', 'vegan', 'lactose-free'],
    times: ['quick', 'standard'],
    budgets: ['low', 'medium'],
    calories: 445,
    protein: 31,
    carbs: 39,
    fats: 19,
    prepMinutes: 12,
    cost: 'Low',
    ingredients: ['220 g firm tofu', '2 slices whole-grain bread', 'Spinach', 'Tomato', 'Turmeric', 'Nutritional yeast'],
    steps: ['Crumble tofu into a hot pan.', 'Add vegetables, turmeric and seasoning.', 'Cook for 7 minutes and serve with toast.'],
    swaps: ['Add mushrooms or peppers.', 'Use a wrap instead of toast for a portable meal.'],
    coachTip: 'Pressing tofu before cooking improves its texture and helps it absorb seasoning.',
  },
  {
    title: 'Chocolate chia protein pudding',
    subtitle: 'A meal-prep pudding with cocoa, chia and plant-based protein.',
    meals: ['breakfast', 'snack'],
    diets: ['vegetarian', 'vegan', 'lactose-free'],
    times: ['quick', 'meal-prep'],
    budgets: ['low', 'medium'],
    calories: 400,
    protein: 29,
    carbs: 38,
    fats: 16,
    prepMinutes: 5,
    cost: 'Low',
    ingredients: ['30 g chia seeds', '250 ml soy milk', '25 g protein powder', '1 tsp cocoa', '½ banana', 'Vanilla'],
    steps: ['Whisk chia, milk, protein powder and cocoa.', 'Refrigerate for at least 2 hours.', 'Top with sliced banana.'],
    swaps: ['Use berries for fewer carbohydrates.', 'Add oats for a larger post-workout portion.'],
    coachTip: 'Stir again after ten minutes to prevent the chia seeds from clumping.',
  },
  {
    title: 'Turkey egg breakfast bowl',
    subtitle: 'A warm savory bowl with lean protein, potatoes and vegetables.',
    meals: ['breakfast', 'lunch', 'post-workout'],
    diets: ['balanced', 'lactose-free'],
    times: ['standard', 'meal-prep'],
    budgets: ['low', 'medium'],
    calories: 585,
    protein: 47,
    carbs: 57,
    fats: 18,
    prepMinutes: 22,
    cost: 'Medium',
    ingredients: ['120 g turkey mince', '2 eggs', '250 g potatoes', 'Spinach', 'Bell pepper', 'Paprika'],
    steps: ['Cook diced potatoes until golden.', 'Brown turkey with peppers and paprika.', 'Add eggs and spinach, then serve together.'],
    swaps: ['Use chicken mince.', 'Replace half the potatoes with zucchini for fewer calories.'],
    coachTip: 'Batch-cook the potatoes and turkey, then add fresh eggs when serving.',
  },
  {
    title: 'Chicken couscous garden bowl',
    subtitle: 'A fresh high-protein bowl that cooks faster than rice.',
    meals: ['lunch', 'dinner', 'post-workout'],
    diets: ['balanced', 'lactose-free'],
    times: ['standard', 'meal-prep'],
    budgets: ['low', 'medium'],
    calories: 610,
    protein: 49,
    carbs: 72,
    fats: 14,
    prepMinutes: 18,
    cost: 'Medium',
    ingredients: ['160 g chicken breast', '80 g dry couscous', 'Cucumber', 'Tomato', 'Parsley', 'Lemon and olive oil'],
    steps: ['Cover couscous with hot water and rest for 5 minutes.', 'Cook the seasoned chicken.', 'Combine with chopped vegetables and lemon.'],
    swaps: ['Use chickpeas for a plant-based bowl.', 'Use bulgur for more texture and fiber.'],
    coachTip: 'Couscous is useful when you need a complete meal but have limited cooking time.',
  },
  {
    title: 'Lean beef burrito bowl',
    subtitle: 'A filling bowl with lean beef, beans, rice and fresh salsa.',
    meals: ['lunch', 'dinner', 'post-workout'],
    diets: ['balanced', 'lactose-free'],
    times: ['standard', 'meal-prep'],
    budgets: ['medium', 'flexible'],
    calories: 735,
    protein: 52,
    carbs: 87,
    fats: 20,
    prepMinutes: 25,
    cost: 'Medium',
    ingredients: ['160 g lean beef mince', '180 g cooked rice', '100 g black beans', 'Corn', 'Tomato salsa', 'Lettuce'],
    steps: ['Brown the beef with cumin and paprika.', 'Warm the rice, beans and corn.', 'Assemble with lettuce and salsa.'],
    swaps: ['Use turkey mince for a leaner bowl.', 'Serve over cauliflower rice for fat loss.'],
    coachTip: 'Choose lean mince and drain excess fat to keep protein high without excessive calories.',
  },
  {
    title: 'Turkey and bean chili',
    subtitle: 'A comforting meal-prep chili with lean protein and plenty of fiber.',
    meals: ['lunch', 'dinner'],
    diets: ['balanced', 'lactose-free'],
    times: ['standard', 'meal-prep'],
    budgets: ['low', 'medium'],
    calories: 560,
    protein: 49,
    carbs: 58,
    fats: 15,
    prepMinutes: 30,
    cost: 'Low',
    ingredients: ['170 g turkey mince', '150 g kidney beans', 'Chopped tomatoes', 'Onion', 'Bell pepper', 'Chili and cumin'],
    steps: ['Brown turkey and onion.', 'Add vegetables, beans, tomatoes and spices.', 'Simmer for 18 minutes.'],
    swaps: ['Use lentils and textured soy protein for a vegan version.', 'Serve with rice for muscle gain.'],
    coachTip: 'Chili often tastes better the next day, making it ideal for four-portion meal prep.',
  },
  {
    title: 'Garlic shrimp noodle stir-fry',
    subtitle: 'Fast noodles with lean seafood, crunchy vegetables and a light sauce.',
    meals: ['lunch', 'dinner', 'post-workout'],
    diets: ['balanced', 'lactose-free'],
    times: ['quick', 'standard'],
    budgets: ['medium', 'flexible'],
    calories: 575,
    protein: 42,
    carbs: 76,
    fats: 11,
    prepMinutes: 14,
    cost: 'Medium',
    ingredients: ['180 g shrimp', '90 g noodles', 'Broccoli', 'Carrot', 'Garlic', 'Soy sauce and lime'],
    steps: ['Cook noodles according to the package.', 'Stir-fry shrimp, garlic and vegetables.', 'Add noodles and sauce, then toss for 2 minutes.'],
    swaps: ['Use chicken or tofu.', 'Choose rice noodles for a gluten-free option.'],
    coachTip: 'Do not overcook shrimp; remove them as soon as they turn opaque.',
  },
  {
    title: 'Mediterranean cod tray',
    subtitle: 'Lean white fish baked with potatoes, tomatoes and olives.',
    meals: ['lunch', 'dinner'],
    diets: ['balanced', 'lactose-free'],
    times: ['standard', 'meal-prep'],
    budgets: ['medium', 'flexible'],
    calories: 540,
    protein: 45,
    carbs: 56,
    fats: 15,
    prepMinutes: 28,
    cost: 'Medium',
    ingredients: ['190 g cod', '280 g baby potatoes', 'Cherry tomatoes', 'Zucchini', 'Olives', 'Lemon and oregano'],
    steps: ['Roast potatoes for 15 minutes.', 'Add cod and vegetables to the tray.', 'Bake for another 12 minutes and finish with lemon.'],
    swaps: ['Use frozen white fish to reduce cost.', 'Replace potatoes with bread or couscous.'],
    coachTip: 'Frozen fish is nutritionally comparable to fresh fish and often more budget friendly.',
  },
  {
    title: 'Beef and sweet potato skillet',
    subtitle: 'A one-pan meal with iron-rich beef and slow-release carbohydrates.',
    meals: ['lunch', 'dinner', 'post-workout'],
    diets: ['balanced', 'lactose-free'],
    times: ['standard', 'meal-prep'],
    budgets: ['medium'],
    calories: 665,
    protein: 46,
    carbs: 68,
    fats: 23,
    prepMinutes: 26,
    cost: 'Medium',
    ingredients: ['160 g lean beef mince', '300 g sweet potato', 'Spinach', 'Onion', 'Tomato', 'Smoked paprika'],
    steps: ['Cook diced sweet potato until tender.', 'Brown beef with onion and paprika.', 'Add spinach and tomato, then combine.'],
    swaps: ['Use turkey mince for less fat.', 'Add beans to stretch the recipe into more portions.'],
    coachTip: 'Pairing iron-rich foods with tomato improves iron absorption.',
  },
  {
    title: 'Chicken pesto pasta salad',
    subtitle: 'A portable pasta salad with chicken, vegetables and a light pesto coating.',
    meals: ['lunch', 'dinner', 'post-workout'],
    diets: ['balanced'],
    times: ['standard', 'meal-prep'],
    budgets: ['medium', 'flexible'],
    calories: 680,
    protein: 50,
    carbs: 81,
    fats: 18,
    prepMinutes: 22,
    cost: 'Medium',
    ingredients: ['160 g chicken breast', '90 g dry pasta', 'Cherry tomatoes', 'Rocket', '20 g pesto', 'Lemon'],
    steps: ['Cook pasta and cool slightly.', 'Cook and slice the chicken.', 'Toss everything with pesto and lemon.'],
    swaps: ['Use lactose-free pesto.', 'Replace chicken with white beans and tofu.'],
    coachTip: 'This keeps well chilled and is practical for lunch after a morning workout.',
  },
  {
    title: 'Chicken hummus pita',
    subtitle: 'A quick pocket filled with lean chicken, hummus and crisp salad.',
    meals: ['lunch', 'snack', 'post-workout'],
    diets: ['balanced', 'lactose-free'],
    times: ['quick'],
    budgets: ['low', 'medium'],
    calories: 505,
    protein: 41,
    carbs: 55,
    fats: 14,
    prepMinutes: 7,
    cost: 'Low',
    ingredients: ['1 whole-wheat pita', '130 g cooked chicken', '35 g hummus', 'Tomato', 'Cucumber', 'Lettuce'],
    steps: ['Warm and open the pita.', 'Spread hummus inside.', 'Fill with chicken and vegetables.'],
    swaps: ['Use falafel or tofu.', 'Add a second pita for a larger recovery meal.'],
    coachTip: 'Cook extra chicken at dinner so this lunch takes less than five minutes the next day.',
  },
  {
    title: 'Peanut tofu noodle bowl',
    subtitle: 'Creamy plant-based noodles with tofu and colorful vegetables.',
    meals: ['lunch', 'dinner', 'post-workout'],
    diets: ['vegetarian', 'vegan', 'lactose-free'],
    times: ['standard', 'meal-prep'],
    budgets: ['low', 'medium'],
    calories: 690,
    protein: 35,
    carbs: 86,
    fats: 24,
    prepMinutes: 24,
    cost: 'Low',
    ingredients: ['200 g tofu', '90 g noodles', 'Carrot', 'Cabbage', '20 g peanut butter', 'Soy sauce and lime'],
    steps: ['Crisp the tofu in a pan.', 'Cook noodles and vegetables.', 'Whisk the sauce and toss everything together.'],
    swaps: ['Use powdered peanut butter for fewer calories.', 'Add edamame for more protein.'],
    coachTip: 'A little hot noodle water makes the peanut sauce smooth without adding more fat.',
  },
  {
    title: 'Teriyaki tempeh rice bowl',
    subtitle: 'Firm tempeh, rice and greens with a savory homemade glaze.',
    meals: ['lunch', 'dinner', 'post-workout'],
    diets: ['vegetarian', 'vegan', 'lactose-free'],
    times: ['standard', 'meal-prep'],
    budgets: ['medium', 'flexible'],
    calories: 640,
    protein: 36,
    carbs: 83,
    fats: 19,
    prepMinutes: 23,
    cost: 'Medium',
    ingredients: ['180 g tempeh', '180 g cooked rice', 'Broccoli', 'Carrot', 'Soy sauce', 'Maple syrup and ginger'],
    steps: ['Steam or sauté the vegetables.', 'Brown sliced tempeh.', 'Add the glaze and serve over rice.'],
    swaps: ['Use tofu if tempeh is unavailable.', 'Replace rice with quinoa for more fiber.'],
    coachTip: 'Steaming tempeh for five minutes before cooking can soften its naturally bitter flavor.',
  },
  {
    title: 'Black bean avocado burrito',
    subtitle: 'A filling vegan burrito with beans, rice and fresh vegetables.',
    meals: ['lunch', 'dinner'],
    diets: ['vegetarian', 'vegan', 'lactose-free'],
    times: ['quick', 'meal-prep'],
    budgets: ['low'],
    calories: 610,
    protein: 23,
    carbs: 94,
    fats: 18,
    prepMinutes: 9,
    cost: 'Low',
    ingredients: ['1 large whole-wheat wrap', '160 g black beans', '120 g cooked rice', '½ avocado', 'Salsa', 'Lettuce'],
    steps: ['Warm beans and rice.', 'Layer all ingredients in the wrap.', 'Fold tightly and toast briefly if desired.'],
    swaps: ['Add tofu or vegan protein strips.', 'Use less rice and more lettuce for fat loss.'],
    coachTip: 'Mash some beans before rolling to help the burrito hold together.',
  },
  {
    title: 'Red lentil bolognese',
    subtitle: 'A high-fiber plant-based pasta sauce designed for batch cooking.',
    meals: ['lunch', 'dinner'],
    diets: ['vegetarian', 'vegan', 'lactose-free'],
    times: ['standard', 'meal-prep'],
    budgets: ['low'],
    calories: 625,
    protein: 29,
    carbs: 104,
    fats: 10,
    prepMinutes: 30,
    cost: 'Low',
    ingredients: ['90 g dry pasta', '90 g red lentils', 'Tomato passata', 'Carrot', 'Onion', 'Garlic and herbs'],
    steps: ['Cook onion, carrot and garlic.', 'Add lentils, passata and water, then simmer.', 'Cook pasta and combine with the sauce.'],
    swaps: ['Use lentil pasta for extra protein.', 'Add mushrooms for more volume.'],
    coachTip: 'Red lentils cook directly in the sauce and create a naturally thick texture.',
  },
  {
    title: 'Seitan kebab plate',
    subtitle: 'A protein-dense vegan plate with spiced seitan, flatbread and salad.',
    meals: ['lunch', 'dinner', 'post-workout'],
    diets: ['vegetarian', 'vegan', 'lactose-free'],
    times: ['standard'],
    budgets: ['medium', 'flexible'],
    calories: 590,
    protein: 48,
    carbs: 69,
    fats: 13,
    prepMinutes: 18,
    cost: 'Medium',
    ingredients: ['180 g seitan', '1 flatbread', 'Tomato', 'Cucumber', 'Red cabbage', 'Tahini lemon sauce'],
    steps: ['Sear sliced seitan with kebab spices.', 'Chop the salad.', 'Serve with warm flatbread and tahini sauce.'],
    swaps: ['Use tofu or soy strips.', 'Serve over rice if flatbread is unavailable.'],
    coachTip: 'Seitan is very high in protein but should be paired with legumes over the day for amino-acid variety.',
  },
  {
    title: 'Mushroom bean risotto',
    subtitle: 'Creamy rice with mushrooms and white beans for extra plant protein.',
    meals: ['lunch', 'dinner'],
    diets: ['vegetarian', 'vegan', 'lactose-free'],
    times: ['standard', 'meal-prep'],
    budgets: ['low', 'medium'],
    calories: 565,
    protein: 22,
    carbs: 88,
    fats: 13,
    prepMinutes: 29,
    cost: 'Low',
    ingredients: ['85 g risotto rice', '150 g white beans', '200 g mushrooms', 'Vegetable stock', 'Onion', 'Nutritional yeast'],
    steps: ['Cook onion and mushrooms.', 'Add rice and gradually stir in stock.', 'Fold in beans and nutritional yeast.'],
    swaps: ['Add peas for more protein.', 'Use parmesan for a vegetarian version.'],
    coachTip: 'White beans make risotto creamier while increasing fiber and protein.',
  },
  {
    title: 'Vegetable egg fried rice',
    subtitle: 'A fast way to turn leftover rice into a balanced protein-rich meal.',
    meals: ['lunch', 'dinner', 'post-workout'],
    diets: ['balanced', 'vegetarian', 'lactose-free'],
    times: ['quick'],
    budgets: ['low'],
    calories: 545,
    protein: 28,
    carbs: 73,
    fats: 16,
    prepMinutes: 9,
    cost: 'Low',
    ingredients: ['220 g cold cooked rice', '3 eggs', '100 g peas', 'Carrot', 'Spring onion', 'Soy sauce'],
    steps: ['Scramble eggs and set aside.', 'Stir-fry rice and vegetables.', 'Return eggs, add soy sauce and toss.'],
    swaps: ['Add chicken, shrimp or tofu.', 'Use cauliflower rice for a lighter meal.'],
    coachTip: 'Cold rice fries better than freshly cooked rice because it contains less surface moisture.',
  },
  {
    title: 'Cottage cheese berry crunch',
    subtitle: 'A sweet high-protein snack requiring no cooking.',
    meals: ['snack', 'breakfast', 'post-workout'],
    diets: ['balanced', 'vegetarian'],
    times: ['quick'],
    budgets: ['low', 'medium'],
    calories: 345,
    protein: 32,
    carbs: 36,
    fats: 9,
    prepMinutes: 3,
    cost: 'Low',
    ingredients: ['220 g cottage cheese', '120 g berries', '20 g granola', 'Cinnamon', '1 tsp honey'],
    steps: ['Add cottage cheese to a bowl.', 'Top with berries and granola.', 'Finish with cinnamon and honey.'],
    swaps: ['Use lactose-free cottage cheese.', 'Replace granola with oats or crushed rice cakes.'],
    coachTip: 'Cottage cheese provides slow-digesting casein protein and works well as an evening snack.',
  },
  {
    title: 'Edamame crunch snack box',
    subtitle: 'A portable plant-based snack with protein, fiber and fresh crunch.',
    meals: ['snack', 'lunch'],
    diets: ['vegetarian', 'vegan', 'lactose-free'],
    times: ['quick', 'meal-prep'],
    budgets: ['low', 'medium'],
    calories: 360,
    protein: 24,
    carbs: 42,
    fats: 12,
    prepMinutes: 7,
    cost: 'Low',
    ingredients: ['180 g shelled edamame', 'Carrot sticks', 'Cucumber', '2 rice cakes', 'Soy sauce', 'Sesame seeds'],
    steps: ['Cook and cool the edamame.', 'Pack with chopped vegetables and rice cakes.', 'Add soy sauce separately.'],
    swaps: ['Replace rice cakes with fruit.', 'Add roasted chickpeas for more crunch.'],
    coachTip: 'Edamame is one of the most protein-dense whole plant foods.',
  },
  {
    title: 'Protein rice cake stack',
    subtitle: 'A fast sweet-and-salty snack with almost no preparation.',
    meals: ['snack', 'breakfast', 'post-workout'],
    diets: ['balanced', 'vegetarian'],
    times: ['quick'],
    budgets: ['low'],
    calories: 375,
    protein: 27,
    carbs: 49,
    fats: 9,
    prepMinutes: 4,
    cost: 'Low',
    ingredients: ['4 rice cakes', '150 g skyr', '1 banana', '15 g peanut butter', 'Cinnamon'],
    steps: ['Spread skyr over the rice cakes.', 'Top with banana slices.', 'Drizzle with peanut butter and cinnamon.'],
    swaps: ['Use soy yogurt and vegan protein powder.', 'Use berries for a lighter version.'],
    coachTip: 'This is easy to digest before training, especially when eaten 60–90 minutes beforehand.',
  },
  {
    title: 'Chocolate cherry recovery smoothie',
    subtitle: 'A refreshing recovery drink with protein, fruit and fast carbohydrates.',
    meals: ['post-workout', 'snack', 'breakfast'],
    diets: ['balanced', 'vegetarian', 'lactose-free'],
    times: ['quick'],
    budgets: ['medium', 'flexible'],
    calories: 465,
    protein: 38,
    carbs: 63,
    fats: 8,
    prepMinutes: 4,
    cost: 'Medium',
    ingredients: ['250 ml lactose-free milk', '30 g protein powder', '150 g frozen cherries', '1 banana', '1 tsp cocoa', 'Ice'],
    steps: ['Add all ingredients to a blender.', 'Blend until smooth.', 'Adjust thickness with water or ice.'],
    swaps: ['Use soy milk for a plant-based version.', 'Add oats for a higher-calorie recovery shake.'],
    coachTip: 'Frozen cherries provide flavor and carbohydrates without needing added sugar.',
  },
  {
    title: 'No-bake oat protein bites',
    subtitle: 'Small meal-prep bites for a practical pre-workout energy boost.',
    meals: ['snack', 'post-workout'],
    diets: ['balanced', 'vegetarian', 'vegan', 'lactose-free'],
    times: ['quick', 'meal-prep'],
    budgets: ['low'],
    calories: 320,
    protein: 20,
    carbs: 37,
    fats: 12,
    prepMinutes: 10,
    cost: 'Low',
    ingredients: ['50 g oats', '20 g protein powder', '20 g peanut butter', '20 g dates', 'Cinnamon', 'A little water'],
    steps: ['Blend or finely chop the dates.', 'Mix all ingredients into a firm dough.', 'Roll into bites and refrigerate.'],
    swaps: ['Use sunflower seed butter.', 'Add cocoa or coconut for a different flavor.'],
    coachTip: 'Keep portions measured because energy bites are compact and easy to overeat.',
  },
  {
    title: 'Hummus protein snack plate',
    subtitle: 'A balanced no-cook plate with hummus, eggs and vegetables.',
    meals: ['snack', 'lunch'],
    diets: ['balanced', 'vegetarian', 'lactose-free'],
    times: ['quick', 'meal-prep'],
    budgets: ['low', 'medium'],
    calories: 440,
    protein: 25,
    carbs: 43,
    fats: 20,
    prepMinutes: 6,
    cost: 'Low',
    ingredients: ['70 g hummus', '2 boiled eggs', 'Carrot', 'Cucumber', '1 small pita', 'Paprika'],
    steps: ['Slice the vegetables and eggs.', 'Add hummus to a small bowl.', 'Serve everything with pita and paprika.'],
    swaps: ['Use edamame instead of eggs for a vegan plate.', 'Use extra vegetables and half the pita for fat loss.'],
    coachTip: 'Boil several eggs in advance to make balanced snacks easier during the week.',
  },
  {
    title: 'High-protein cereal recovery bowl',
    subtitle: 'A very fast post-workout bowl when cooking is not practical.',
    meals: ['post-workout', 'breakfast', 'snack'],
    diets: ['balanced', 'vegetarian'],
    times: ['quick'],
    budgets: ['low', 'medium'],
    calories: 525,
    protein: 39,
    carbs: 78,
    fats: 8,
    prepMinutes: 3,
    cost: 'Low',
    ingredients: ['60 g whole-grain cereal', '300 ml high-protein milk', '150 g skyr', '1 banana', 'Cinnamon'],
    steps: ['Add cereal to a bowl.', 'Pour over milk.', 'Top with skyr, banana and cinnamon.'],
    swaps: ['Use soy milk and plant protein yogurt.', 'Replace banana with berries for fewer carbohydrates.'],
    coachTip: 'This gives rapid carbohydrates plus enough protein for recovery after a late session.',
  },
];

const GOAL_ADJUSTMENTS: Record<NutritionGoal, { calories: number; protein: number; carbs: number; fats: number; tip: string }> = {
  lose: {
    calories: -110,
    protein: 5,
    carbs: -18,
    fats: -4,
    tip: 'The portion is adjusted for fat loss: protein stays high while energy-dense extras are reduced.',
  },
  maintain: {
    calories: 0,
    protein: 0,
    carbs: 0,
    fats: 0,
    tip: 'The portion is balanced for maintenance, daily energy and training recovery.',
  },
  gain: {
    calories: 180,
    protein: 7,
    carbs: 28,
    fats: 5,
    tip: 'The portion is adjusted for muscle gain with extra protein and training carbohydrates.',
  },
};

export function createMealRecommendation(answers: AssistantAnswers): MealRecommendation {
  const compatibleMeals = MEALS.filter(
    (meal) => meal.meals.includes(answers.meal) && meal.diets.includes(answers.diet),
  );
  const candidateMeals = compatibleMeals.length
    ? compatibleMeals
    : MEALS.filter((meal) => meal.diets.includes(answers.diet));
  const scoredMeals = candidateMeals.map((meal) => {
    let score = 0;
    if (meal.times.includes(answers.time)) score += 4;
    if (meal.budgets.includes(answers.budget)) score += 3;
    if (answers.goal === 'gain' && meal.protein >= 35) score += 3;
    if (answers.goal === 'lose' && meal.calories <= 520) score += 3;
    return { meal, score };
  }).sort((first, second) => second.score - first.score);

  const topScore = scoredMeals[0].score;
  const closeMatches = scoredMeals
    .filter((candidate) => candidate.score >= topScore - 2)
    .slice(0, 8);
  const answerKey = `${answers.goal}-${answers.meal}-${answers.diet}-${answers.time}-${answers.budget}`;
  const selectedIndex = getNextRecommendationIndex(answerKey, closeMatches.length);
  const selected = closeMatches[selectedIndex].meal;
  const adjustment = GOAL_ADJUSTMENTS[answers.goal];

  return {
    title: selected.title,
    subtitle: selected.subtitle,
    calories: Math.max(220, selected.calories + adjustment.calories),
    protein: Math.max(15, selected.protein + adjustment.protein),
    carbs: Math.max(15, selected.carbs + adjustment.carbs),
    fats: Math.max(5, selected.fats + adjustment.fats),
    prepMinutes: selected.prepMinutes,
    cost: selected.cost,
    ingredients: [...selected.ingredients],
    steps: [...selected.steps],
    swaps: [...selected.swaps],
    coachTip: `${adjustment.tip} ${selected.coachTip}`,
  };
}

const recommendationIndexes = new Map<string, number>();

function getNextRecommendationIndex(answerKey: string, resultCount: number): number {
  const currentIndex = recommendationIndexes.get(answerKey) ?? 0;
  recommendationIndexes.set(answerKey, (currentIndex + 1) % resultCount);
  return currentIndex % resultCount;
}
