export type NutritionGoal = 'lose' | 'maintain' | 'gain';
export type MealType = 'breakfast' | 'lunch' | 'dinner' | 'snack' | 'post-workout';
export type DietType = 'balanced' | 'vegetarian' | 'vegan' | 'lactose-free';
export type PrepTime = 'quick' | 'standard' | 'meal-prep';
export type BudgetType = 'low' | 'medium' | 'flexible';
export type AssistantStep = 'goal' | 'meal' | 'diet' | 'time' | 'budget' | 'result';

export interface AssistantAnswers {
  goal: NutritionGoal;
  meal: MealType;
  diet: DietType;
  time: PrepTime;
  budget: BudgetType;
}

export interface AssistantOption {
  value: string;
  label: string;
  description: string;
  icon: string;
}

export interface MealRecommendation {
  title: string;
  subtitle: string;
  calories: number;
  protein: number;
  carbs: number;
  fats: number;
  prepMinutes: number;
  cost: string;
  ingredients: string[];
  steps: string[];
  swaps: string[];
  coachTip: string;
}

interface MealTemplate extends MealRecommendation {
  meals: MealType[];
  diets: DietType[];
  times: PrepTime[];
  budgets: BudgetType[];
}

export const ASSISTANT_OPTIONS: Record<Exclude<AssistantStep, 'result'>, AssistantOption[]> = {
  goal: [
    { value: 'lose', label: 'Fat loss', description: 'High volume, filling meals and controlled calories.', icon: 'M4 6l6 6 4-4 6 10m-5 0h5v-5' },
    { value: 'maintain', label: 'Maintain', description: 'Balanced portions for energy and recovery.', icon: 'M12 3v17m-5 0h10M4 7h16M6 7l-3 7h6L6 7m12 0-3 7h6l-3-7' },
    { value: 'gain', label: 'Build muscle', description: 'More calories, protein and training fuel.', icon: 'M3 9v6m3-8v10m0-5h12m0-5v10m3-8v6' },
  ],
  meal: [
    { value: 'breakfast', label: 'Breakfast', description: 'Start the day with steady energy.', icon: 'M3 17h18M5 17a7 7 0 0 1 14 0M12 10V7m-2 0h4M7 4V2m10 2V2' },
    { value: 'lunch', label: 'Lunch', description: 'A complete meal for the middle of the day.', icon: 'M3 11h18c0 5-4 8-9 8s-9-3-9-8ZM8 8c-3 0-4-2-4-4 3 0 5 1 5 4m3 0V3m4 5c3 0 4-2 4-4-3 0-5 1-5 4' },
    { value: 'dinner', label: 'Dinner', description: 'Recovery-focused and easy to digest.', icon: 'M4 3v6m3-6v6M2 6h7M5.5 9v12M19 3c-4 4-4 8 0 8V3m0 8v10' },
    { value: 'snack', label: 'Snack', description: 'Small, practical and protein-aware.', icon: 'M12 7c-3-3-9-1-9 4 0 6 4 10 7 9h4c3 1 7-3 7-9 0-5-6-7-9-4Zm0 0V3m0 1c2-3 5-3 6-2-1 3-3 4-6 2' },
    { value: 'post-workout', label: 'Post-workout', description: 'Protein and carbohydrates for recovery.', icon: 'M7 7h10l-1 14H8L7 7Zm-2 0h14M12 7V3l5-1' },
  ],
  diet: [
    { value: 'balanced', label: 'No restrictions', description: 'Uses a wide range of foods.', icon: 'M12 4a8 8 0 1 0 0 16 8 8 0 0 0 0-16Zm-3 8 2 2 4-4' },
    { value: 'vegetarian', label: 'Vegetarian', description: 'No meat or fish.', icon: 'M4 4c9-1 16 3 16 12-9 3-16-2-16-12Zm3 3 10 10M9 9v5m4-1h5' },
    { value: 'vegan', label: 'Vegan', description: 'Only plant-based ingredients.', icon: 'M12 21V10M12 14C5 14 3 10 3 6c6 0 9 3 9 8Zm0-4c0-5 3-8 9-8 0 5-3 8-9 8Z' },
    { value: 'lactose-free', label: 'Lactose-free', description: 'No regular dairy products.', icon: 'M9 3h6v4l3 4v10H6V11l3-4V3Zm-3 10h12M9 3h6' },
  ],
  time: [
    { value: 'quick', label: '10 min or less', description: 'Quick active prep. Minimal cleanup.', icon: 'm13 2-9 12h7l-1 8 10-13h-7l1-7Z' },
    { value: 'standard', label: 'Up to 30 min', description: 'Time for a freshly cooked meal.', icon: 'M9 2h6M12 5a8 8 0 1 0 0 16 8 8 0 0 0 0-16Zm0 4v4l3 2m4-10 2 2' },
    { value: 'meal-prep', label: 'Meal prep', description: 'Cook several portions at once.', icon: 'M5 4h14a2 2 0 0 1 2 2v14H3V6a2 2 0 0 1 2-2Zm-2 6h18m-11 0v10m0-5h11' },
  ],
  budget: [
    { value: 'low', label: 'Budget friendly', description: 'Simple and affordable staples.', icon: 'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18Zm2 5h-3a2 2 0 0 0 0 4h2a2 2 0 0 1 0 4h-3m2-9v10' },
    { value: 'medium', label: 'Balanced budget', description: 'Good variety without overspending.', icon: 'M3 6h18v12H3V6Zm9 3a3 3 0 1 0 0 6 3 3 0 0 0 0-6ZM6 9v6m12-6v6' },
    { value: 'flexible', label: 'Flexible', description: 'Prioritizes taste and nutrition.', icon: 'M3 7h18v14H3V7Zm0 0V4h15v3m-2 5h5v5h-5v-5Z' },
  ],
};

const MEALS: MealTemplate[] = [
  {
    title: 'Protein overnight oats',
    subtitle: 'Creamy oats with berries, seeds and a high-protein base.',
    meals: ['breakfast', 'snack'],
    diets: ['balanced', 'vegetarian'],
    times: ['quick', 'meal-prep'],
    budgets: ['low', 'medium'],
    calories: 455,
    protein: 35,
    carbs: 57,
    fats: 11,
    prepMinutes: 7,
    cost: 'Low',
    ingredients: ['60 g oats', '200 g Greek yogurt', '100 ml milk', '100 g berries', '10 g chia seeds', 'Cinnamon'],
    steps: ['Mix oats, yogurt, milk and chia.', 'Refrigerate overnight or at least 2 hours.', 'Add berries and cinnamon before eating.'],
    swaps: ['Use soy yogurt and soy milk for a vegan version.', 'Replace berries with banana for more carbohydrates.'],
    coachTip: 'Prepare three jars at once to make breakfast automatic on busy training days.',
  },
  {
    title: 'Egg and avocado breakfast wrap',
    subtitle: 'A warm, filling wrap with protein, fiber and healthy fats.',
    meals: ['breakfast', 'post-workout'],
    diets: ['balanced', 'vegetarian', 'lactose-free'],
    times: ['quick', 'standard'],
    budgets: ['low', 'medium'],
    calories: 520,
    protein: 31,
    carbs: 48,
    fats: 23,
    prepMinutes: 10,
    cost: 'Low',
    ingredients: ['3 eggs', '1 whole-wheat wrap', '½ avocado', 'Tomato', 'Spinach', 'Salt and pepper'],
    steps: ['Scramble the eggs with spinach.', 'Warm the wrap.', 'Add eggs, avocado and tomato, then roll tightly.'],
    swaps: ['Use egg whites for fewer calories.', 'Add salsa or hot sauce without significantly increasing calories.'],
    coachTip: 'For fat loss, use 2 eggs and extra vegetables. For muscle gain, add a second wrap.',
  },
  {
    title: 'Tofu berry smoothie bowl',
    subtitle: 'A thick plant-based bowl with fruit and complete soy protein.',
    meals: ['breakfast', 'snack', 'post-workout'],
    diets: ['vegan', 'lactose-free'],
    times: ['quick'],
    budgets: ['medium', 'flexible'],
    calories: 430,
    protein: 28,
    carbs: 61,
    fats: 10,
    prepMinutes: 6,
    cost: 'Medium',
    ingredients: ['180 g silken tofu', '1 frozen banana', '150 g frozen berries', '150 ml soy milk', '20 g oats', '10 g peanut butter'],
    steps: ['Blend tofu, fruit, soy milk and oats until thick.', 'Pour into a bowl.', 'Top with peanut butter and a few berries.'],
    swaps: ['Use mango instead of berries.', 'Add vegan protein powder to increase protein by 20–25 g.'],
    coachTip: 'Soy milk and tofu provide more protein than most other plant-based alternatives.',
  },
  {
    title: 'Chicken rice power bowl',
    subtitle: 'A reliable high-protein bowl for performance and recovery.',
    meals: ['lunch', 'dinner', 'post-workout'],
    diets: ['balanced', 'lactose-free'],
    times: ['standard', 'meal-prep'],
    budgets: ['low', 'medium'],
    calories: 650,
    protein: 52,
    carbs: 78,
    fats: 14,
    prepMinutes: 25,
    cost: 'Medium',
    ingredients: ['170 g chicken breast', '200 g cooked rice', '150 g mixed vegetables', '1 tsp olive oil', 'Soy sauce', 'Garlic and paprika'],
    steps: ['Season and cook the chicken.', 'Sauté or steam the vegetables.', 'Serve over rice and finish with soy sauce.'],
    swaps: ['Replace chicken with turkey.', 'Use cauliflower rice for a lower-calorie version.'],
    coachTip: 'Cook four portions and store the sauce separately so the rice keeps its texture.',
  },
  {
    title: 'Salmon potato recovery plate',
    subtitle: 'Omega-3 fats, lean protein and easy-to-digest carbohydrates.',
    meals: ['lunch', 'dinner', 'post-workout'],
    diets: ['balanced', 'lactose-free'],
    times: ['standard'],
    budgets: ['medium', 'flexible'],
    calories: 690,
    protein: 46,
    carbs: 63,
    fats: 27,
    prepMinutes: 28,
    cost: 'High',
    ingredients: ['170 g salmon', '300 g potatoes', 'Green beans', '1 tsp olive oil', 'Lemon', 'Dill and garlic'],
    steps: ['Roast or air-fry the potatoes.', 'Season and cook the salmon.', 'Steam the beans and serve with lemon.'],
    swaps: ['Use canned tuna for a cheaper option.', 'Replace potatoes with rice after intense training.'],
    coachTip: 'This is especially useful after demanding sessions because it combines protein, carbs and omega-3 fats.',
  },
  {
    title: 'Turkey hummus crunch wrap',
    subtitle: 'Fast, portable and balanced for lunch or a substantial snack.',
    meals: ['lunch', 'snack'],
    diets: ['balanced', 'lactose-free'],
    times: ['quick'],
    budgets: ['low', 'medium'],
    calories: 480,
    protein: 38,
    carbs: 51,
    fats: 14,
    prepMinutes: 8,
    cost: 'Low',
    ingredients: ['1 whole-wheat wrap', '120 g sliced turkey', '40 g hummus', 'Lettuce', 'Cucumber', 'Bell pepper'],
    steps: ['Spread hummus over the wrap.', 'Layer turkey and vegetables.', 'Roll tightly and slice in half.'],
    swaps: ['Use cooked chicken leftovers.', 'Add a second wrap for a higher-calorie meal.'],
    coachTip: 'Keep washed vegetables ready in the fridge to make this meal in under five minutes.',
  },
  {
    title: 'Lentil quinoa meal-prep bowl',
    subtitle: 'Plant-based protein, fiber and slow-release carbohydrates.',
    meals: ['lunch', 'dinner'],
    diets: ['vegetarian', 'vegan', 'lactose-free'],
    times: ['standard', 'meal-prep'],
    budgets: ['low', 'medium'],
    calories: 570,
    protein: 29,
    carbs: 85,
    fats: 13,
    prepMinutes: 30,
    cost: 'Low',
    ingredients: ['180 g cooked lentils', '150 g cooked quinoa', 'Roasted peppers', 'Spinach', '1 tbsp tahini', 'Lemon and cumin'],
    steps: ['Cook quinoa and warm the lentils.', 'Roast or sauté the vegetables.', 'Mix tahini with lemon and water, then assemble.'],
    swaps: ['Use brown rice instead of quinoa.', 'Add tofu or edamame for more protein.'],
    coachTip: 'Legumes and grains complement each other and create a stronger amino-acid profile.',
  },
  {
    title: 'Creamy high-protein pasta',
    subtitle: 'Comforting pasta with a lighter protein-rich sauce.',
    meals: ['lunch', 'dinner', 'post-workout'],
    diets: ['balanced', 'vegetarian'],
    times: ['standard', 'meal-prep'],
    budgets: ['low', 'medium'],
    calories: 720,
    protein: 48,
    carbs: 98,
    fats: 16,
    prepMinutes: 22,
    cost: 'Medium',
    ingredients: ['100 g dry pasta', '180 g cottage cheese', 'Tomato sauce', 'Spinach', '15 g vegetarian hard cheese', 'Garlic and basil'],
    steps: ['Cook the pasta and reserve a little water.', 'Blend cottage cheese with tomato sauce.', 'Warm the sauce, add spinach and combine with pasta.'],
    swaps: ['Use lentil pasta for more protein.', 'Use lactose-free cottage cheese if needed.'],
    coachTip: 'This is a strong post-workout choice when you need both protein and a larger carbohydrate serving.',
  },
  {
    title: 'Chickpea vegetable curry',
    subtitle: 'A warming plant-based dinner built from affordable pantry foods.',
    meals: ['lunch', 'dinner'],
    diets: ['vegetarian', 'vegan', 'lactose-free'],
    times: ['standard', 'meal-prep'],
    budgets: ['low'],
    calories: 590,
    protein: 23,
    carbs: 91,
    fats: 15,
    prepMinutes: 27,
    cost: 'Low',
    ingredients: ['200 g chickpeas', '150 g cooked rice', 'Tomato', 'Light coconut milk', 'Mixed vegetables', 'Curry powder'],
    steps: ['Cook vegetables with curry powder.', 'Add tomato, coconut milk and chickpeas.', 'Simmer for 12 minutes and serve with rice.'],
    swaps: ['Add tofu for more protein.', 'Use less rice and more vegetables for fat loss.'],
    coachTip: 'Freeze individual portions so you always have a balanced meal available.',
  },
  {
    title: 'Greek yogurt protein cup',
    subtitle: 'A no-cook snack with protein, fruit and a little crunch.',
    meals: ['snack', 'breakfast'],
    diets: ['balanced', 'vegetarian'],
    times: ['quick'],
    budgets: ['low', 'medium'],
    calories: 330,
    protein: 30,
    carbs: 37,
    fats: 8,
    prepMinutes: 3,
    cost: 'Low',
    ingredients: ['250 g Greek yogurt', '1 small banana', '15 g walnuts', 'Cinnamon', '1 tsp honey'],
    steps: ['Add yogurt to a bowl.', 'Top with sliced banana, walnuts and cinnamon.', 'Add honey if desired.'],
    swaps: ['Use lactose-free yogurt.', 'Replace walnuts with cereal for more carbohydrates.'],
    coachTip: 'This snack works well one to two hours before training because it is easy to digest.',
  },
  {
    title: 'Tuna and bean protein salad',
    subtitle: 'High protein, high fiber and ready in minutes.',
    meals: ['lunch', 'dinner', 'snack'],
    diets: ['balanced', 'lactose-free'],
    times: ['quick'],
    budgets: ['low'],
    calories: 470,
    protein: 44,
    carbs: 42,
    fats: 13,
    prepMinutes: 7,
    cost: 'Low',
    ingredients: ['1 can tuna', '150 g white beans', 'Tomato', 'Cucumber', 'Red onion', 'Lemon and 1 tsp olive oil'],
    steps: ['Drain the tuna and beans.', 'Chop the vegetables.', 'Mix everything with lemon, oil, salt and pepper.'],
    swaps: ['Use chickpeas and tofu for a plant-based version.', 'Serve with bread after training.'],
    coachTip: 'Rinsing canned beans lowers sodium and improves their texture.',
  },
  {
    title: 'Peanut banana recovery shake',
    subtitle: 'Fast carbohydrates and protein when a full meal is not practical.',
    meals: ['post-workout', 'snack', 'breakfast'],
    diets: ['balanced', 'vegetarian', 'lactose-free', 'vegan'],
    times: ['quick'],
    budgets: ['low', 'medium', 'flexible'],
    calories: 510,
    protein: 34,
    carbs: 68,
    fats: 14,
    prepMinutes: 4,
    cost: 'Low',
    ingredients: ['1 banana', '300 ml soy milk', '30 g plant protein powder', '20 g peanut butter', '30 g oats', 'Ice and cinnamon'],
    steps: ['Add all ingredients to a blender.', 'Blend until smooth.', 'Drink immediately after training or alongside a lighter meal.'],
    swaps: ['Use berries for fewer carbohydrates.', 'Add another banana for muscle gain.'],
    coachTip: 'Choose a plant or whey protein that provides around 20–25 g protein per serving.',
  },
  {
    title: 'Apple cinnamon skyr oats',
    subtitle: 'A crisp, creamy breakfast with slow carbohydrates and plenty of protein.',
    meals: ['breakfast', 'snack'],
    diets: ['balanced', 'vegetarian'],
    times: ['quick', 'meal-prep'],
    budgets: ['low', 'medium'],
    calories: 420,
    protein: 34,
    carbs: 55,
    fats: 7,
    prepMinutes: 6,
    cost: 'Low',
    ingredients: ['250 g skyr', '50 g oats', '1 apple', 'Cinnamon', '10 g pumpkin seeds', '1 tsp honey'],
    steps: ['Dice the apple.', 'Mix skyr, oats and cinnamon.', 'Top with apple, seeds and honey.'],
    swaps: ['Use lactose-free skyr.', 'Microwave the apple with cinnamon for a warm version.'],
    coachTip: 'The combination of protein and fiber helps keep hunger controlled through the morning.',
  },
  {
    title: 'Banana protein pancakes',
    subtitle: 'Soft three-ingredient pancakes that work for breakfast or recovery.',
    meals: ['breakfast', 'post-workout'],
    diets: ['balanced', 'vegetarian', 'lactose-free'],
    times: ['quick', 'standard'],
    budgets: ['low'],
    calories: 495,
    protein: 36,
    carbs: 62,
    fats: 12,
    prepMinutes: 10,
    cost: 'Low',
    ingredients: ['1 banana', '2 eggs', '40 g oats', '25 g plant protein powder', 'Cinnamon', '100 g berries'],
    steps: ['Blend banana, eggs, oats and protein powder.', 'Cook small pancakes in a non-stick pan.', 'Serve with berries and cinnamon.'],
    swaps: ['Use soy protein and a flax egg for a plant-based version.', 'Add yogurt for an extra creamy topping.'],
    coachTip: 'Small pancakes flip more easily and cook evenly without much oil.',
  },
  {
    title: 'Savory cottage cheese toast',
    subtitle: 'Crunchy toast topped with creamy protein and fresh vegetables.',
    meals: ['breakfast', 'snack', 'lunch'],
    diets: ['balanced', 'vegetarian'],
    times: ['quick'],
    budgets: ['low', 'medium'],
    calories: 390,
    protein: 31,
    carbs: 43,
    fats: 11,
    prepMinutes: 5,
    cost: 'Low',
    ingredients: ['2 slices whole-grain bread', '180 g cottage cheese', 'Tomato', 'Cucumber', 'Black pepper', 'Fresh herbs'],
    steps: ['Toast the bread.', 'Season the cottage cheese.', 'Top the toast with cottage cheese and vegetables.'],
    swaps: ['Use lactose-free cottage cheese.', 'Add smoked salmon for more protein and omega-3 fats.'],
    coachTip: 'Choose bread with at least 5 g fiber per 100 g for better fullness.',
  },
  {
    title: 'Mediterranean tofu scramble',
    subtitle: 'A colorful plant-based breakfast with vegetables and high-protein tofu.',
    meals: ['breakfast', 'lunch'],
    diets: ['vegetarian', 'vegan', 'lactose-free'],
    times: ['quick', 'standard'],
    budgets: ['low', 'medium'],
    calories: 445,
    protein: 31,
    carbs: 39,
    fats: 19,
    prepMinutes: 12,
    cost: 'Low',
    ingredients: ['220 g firm tofu', '2 slices whole-grain bread', 'Spinach', 'Tomato', 'Turmeric', 'Nutritional yeast'],
    steps: ['Crumble tofu into a hot pan.', 'Add vegetables, turmeric and seasoning.', 'Cook for 7 minutes and serve with toast.'],
    swaps: ['Add mushrooms or peppers.', 'Use a wrap instead of toast for a portable meal.'],
    coachTip: 'Pressing tofu before cooking improves its texture and helps it absorb seasoning.',
  },
  {
    title: 'Chocolate chia protein pudding',
    subtitle: 'A meal-prep pudding with cocoa, chia and plant-based protein.',
    meals: ['breakfast', 'snack'],
    diets: ['vegetarian', 'vegan', 'lactose-free'],
    times: ['quick', 'meal-prep'],
    budgets: ['low', 'medium'],
    calories: 400,
    protein: 29,
    carbs: 38,
    fats: 16,
    prepMinutes: 5,
    cost: 'Low',
    ingredients: ['30 g chia seeds', '250 ml soy milk', '25 g plant protein powder', '1 tsp cocoa', '½ banana', 'Vanilla'],
    steps: ['Whisk chia, milk, protein powder and cocoa.', 'Refrigerate for at least 2 hours.', 'Top with sliced banana.'],
    swaps: ['Use berries for fewer carbohydrates.', 'Add oats for a larger post-workout portion.'],
    coachTip: 'Stir again after ten minutes to prevent the chia seeds from clumping.',
  },
  {
    title: 'Turkey egg breakfast bowl',
    subtitle: 'A warm savory bowl with lean protein, potatoes and vegetables.',
    meals: ['breakfast', 'lunch', 'post-workout'],
    diets: ['balanced', 'lactose-free'],
    times: ['standard', 'meal-prep'],
    budgets: ['low', 'medium'],
    calories: 585,
    protein: 47,
    carbs: 57,
    fats: 18,
    prepMinutes: 22,
    cost: 'Medium',
    ingredients: ['120 g turkey mince', '2 eggs', '250 g potatoes', 'Spinach', 'Bell pepper', 'Paprika'],
    steps: ['Cook diced potatoes until golden.', 'Brown turkey with peppers and paprika.', 'Add eggs and spinach, then serve together.'],
    swaps: ['Use chicken mince.', 'Replace half the potatoes with zucchini for fewer calories.'],
    coachTip: 'Batch-cook the potatoes and turkey, then add fresh eggs when serving.',
  },
  {
    title: 'Chicken couscous garden bowl',
    subtitle: 'A fresh high-protein bowl that cooks faster than rice.',
    meals: ['lunch', 'dinner', 'post-workout'],
    diets: ['balanced', 'lactose-free'],
    times: ['standard', 'meal-prep'],
    budgets: ['low', 'medium'],
    calories: 610,
    protein: 49,
    carbs: 72,
    fats: 14,
    prepMinutes: 18,
    cost: 'Medium',
    ingredients: ['160 g chicken breast', '80 g dry couscous', 'Cucumber', 'Tomato', 'Parsley', 'Lemon and olive oil'],
    steps: ['Cover couscous with hot water and rest for 5 minutes.', 'Cook the seasoned chicken.', 'Combine with chopped vegetables and lemon.'],
    swaps: ['Use chickpeas for a plant-based bowl.', 'Use bulgur for more texture and fiber.'],
    coachTip: 'Couscous is useful when you need a complete meal but have limited cooking time.',
  },
  {
    title: 'Lean beef burrito bowl',
    subtitle: 'A filling bowl with lean beef, beans, rice and fresh salsa.',
    meals: ['lunch', 'dinner', 'post-workout'],
    diets: ['balanced', 'lactose-free'],
    times: ['standard', 'meal-prep'],
    budgets: ['medium', 'flexible'],
    calories: 735,
    protein: 52,
    carbs: 87,
    fats: 20,
    prepMinutes: 25,
    cost: 'Medium',
    ingredients: ['160 g lean beef mince', '180 g cooked rice', '100 g black beans', 'Corn', 'Tomato salsa', 'Lettuce'],
    steps: ['Brown the beef with cumin and paprika.', 'Warm the rice, beans and corn.', 'Assemble with lettuce and salsa.'],
    swaps: ['Use turkey mince for a leaner bowl.', 'Serve over cauliflower rice for fat loss.'],
    coachTip: 'Choose lean mince and drain excess fat to keep protein high without excessive calories.',
  },
  {
    title: 'Turkey and bean chili',
    subtitle: 'A comforting meal-prep chili with lean protein and plenty of fiber.',
    meals: ['lunch', 'dinner'],
    diets: ['balanced', 'lactose-free'],
    times: ['standard', 'meal-prep'],
    budgets: ['low', 'medium'],
    calories: 560,
    protein: 49,
    carbs: 58,
    fats: 15,
    prepMinutes: 30,
    cost: 'Low',
    ingredients: ['170 g turkey mince', '150 g kidney beans', 'Chopped tomatoes', 'Onion', 'Bell pepper', 'Chili and cumin'],
    steps: ['Brown turkey and onion.', 'Add vegetables, beans, tomatoes and spices.', 'Simmer for 18 minutes.'],
    swaps: ['Use lentils and textured soy protein for a vegan version.', 'Serve with rice for muscle gain.'],
    coachTip: 'Chili often tastes better the next day, making it ideal for four-portion meal prep.',
  },
  {
    title: 'Garlic shrimp noodle stir-fry',
    subtitle: 'Fast noodles with lean seafood, crunchy vegetables and a light sauce.',
    meals: ['lunch', 'dinner', 'post-workout'],
    diets: ['balanced', 'lactose-free'],
    times: ['quick', 'standard'],
    budgets: ['medium', 'flexible'],
    calories: 575,
    protein: 42,
    carbs: 76,
    fats: 11,
    prepMinutes: 14,
    cost: 'Medium',
    ingredients: ['180 g shrimp', '90 g noodles', 'Broccoli', 'Carrot', 'Garlic', 'Soy sauce and lime'],
    steps: ['Cook noodles according to the package.', 'Stir-fry shrimp, garlic and vegetables.', 'Add noodles and sauce, then toss for 2 minutes.'],
    swaps: ['Use chicken or tofu.', 'Choose rice noodles for a gluten-free option.'],
    coachTip: 'Do not overcook shrimp; remove them as soon as they turn opaque.',
  },
  {
    title: 'Mediterranean cod tray',
    subtitle: 'Lean white fish baked with potatoes, tomatoes and olives.',
    meals: ['lunch', 'dinner'],
    diets: ['balanced', 'lactose-free'],
    times: ['standard', 'meal-prep'],
    budgets: ['medium', 'flexible'],
    calories: 540,
    protein: 45,
    carbs: 56,
    fats: 15,
    prepMinutes: 28,
    cost: 'Medium',
    ingredients: ['190 g cod', '280 g baby potatoes', 'Cherry tomatoes', 'Zucchini', 'Olives', 'Lemon and oregano'],
    steps: ['Roast potatoes for 15 minutes.', 'Add cod and vegetables to the tray.', 'Bake for another 12 minutes and finish with lemon.'],
    swaps: ['Use frozen white fish to reduce cost.', 'Replace potatoes with bread or couscous.'],
    coachTip: 'Frozen fish is nutritionally comparable to fresh fish and often more budget friendly.',
  },
  {
    title: 'Beef and sweet potato skillet',
    subtitle: 'A one-pan meal with iron-rich beef and slow-release carbohydrates.',
    meals: ['lunch', 'dinner', 'post-workout'],
    diets: ['balanced', 'lactose-free'],
    times: ['standard', 'meal-prep'],
    budgets: ['medium'],
    calories: 665,
    protein: 46,
    carbs: 68,
    fats: 23,
    prepMinutes: 26,
    cost: 'Medium',
    ingredients: ['160 g lean beef mince', '300 g sweet potato', 'Spinach', 'Onion', 'Tomato', 'Smoked paprika'],
    steps: ['Cook diced sweet potato until tender.', 'Brown beef with onion and paprika.', 'Add spinach and tomato, then combine.'],
    swaps: ['Use turkey mince for less fat.', 'Add beans to stretch the recipe into more portions.'],
    coachTip: 'Pairing iron-rich foods with tomato improves iron absorption.',
  },
  {
    title: 'Chicken pesto pasta salad',
    subtitle: 'A portable pasta salad with chicken, vegetables and a light pesto coating.',
    meals: ['lunch', 'dinner', 'post-workout'],
    diets: ['balanced'],
    times: ['standard', 'meal-prep'],
    budgets: ['medium', 'flexible'],
    calories: 680,
    protein: 50,
    carbs: 81,
    fats: 18,
    prepMinutes: 22,
    cost: 'Medium',
    ingredients: ['160 g chicken breast', '90 g dry pasta', 'Cherry tomatoes', 'Rocket', '20 g pesto', 'Lemon'],
    steps: ['Cook pasta and cool slightly.', 'Cook and slice the chicken.', 'Toss everything with pesto and lemon.'],
    swaps: ['Use lactose-free pesto.', 'Replace chicken with white beans and tofu.'],
    coachTip: 'This keeps well chilled and is practical for lunch after a morning workout.',
  },
  {
    title: 'Chicken hummus pita',
    subtitle: 'A quick pocket filled with lean chicken, hummus and crisp salad.',
    meals: ['lunch', 'snack', 'post-workout'],
    diets: ['balanced', 'lactose-free'],
    times: ['quick'],
    budgets: ['low', 'medium'],
    calories: 505,
    protein: 41,
    carbs: 55,
    fats: 14,
    prepMinutes: 7,
    cost: 'Low',
    ingredients: ['1 whole-wheat pita', '130 g cooked chicken', '35 g hummus', 'Tomato', 'Cucumber', 'Lettuce'],
    steps: ['Warm and open the pita.', 'Spread hummus inside.', 'Fill with chicken and vegetables.'],
    swaps: ['Use falafel or tofu.', 'Add a second pita for a larger recovery meal.'],
    coachTip: 'Cook extra chicken at dinner so this lunch takes less than five minutes the next day.',
  },
  {
    title: 'Peanut tofu noodle bowl',
    subtitle: 'Creamy plant-based noodles with tofu and colorful vegetables.',
    meals: ['lunch', 'dinner', 'post-workout'],
    diets: ['vegetarian', 'vegan', 'lactose-free'],
    times: ['standard', 'meal-prep'],
    budgets: ['low', 'medium'],
    calories: 690,
    protein: 35,
    carbs: 86,
    fats: 24,
    prepMinutes: 24,
    cost: 'Low',
    ingredients: ['200 g tofu', '90 g noodles', 'Carrot', 'Cabbage', '20 g peanut butter', 'Soy sauce and lime'],
    steps: ['Crisp the tofu in a pan.', 'Cook noodles and vegetables.', 'Whisk the sauce and toss everything together.'],
    swaps: ['Use powdered peanut butter for fewer calories.', 'Add edamame for more protein.'],
    coachTip: 'A little hot noodle water makes the peanut sauce smooth without adding more fat.',
  },
  {
    title: 'Teriyaki tempeh rice bowl',
    subtitle: 'Firm tempeh, rice and greens with a savory homemade glaze.',
    meals: ['lunch', 'dinner', 'post-workout'],
    diets: ['vegetarian', 'vegan', 'lactose-free'],
    times: ['standard', 'meal-prep'],
    budgets: ['medium', 'flexible'],
    calories: 640,
    protein: 36,
    carbs: 83,
    fats: 19,
    prepMinutes: 23,
    cost: 'Medium',
    ingredients: ['180 g tempeh', '180 g cooked rice', 'Broccoli', 'Carrot', 'Soy sauce', 'Maple syrup and ginger'],
    steps: ['Steam or sauté the vegetables.', 'Brown sliced tempeh.', 'Add the glaze and serve over rice.'],
    swaps: ['Use tofu if tempeh is unavailable.', 'Replace rice with quinoa for more fiber.'],
    coachTip: 'Steaming tempeh for five minutes before cooking can soften its naturally bitter flavor.',
  },
  {
    title: 'Black bean avocado burrito',
    subtitle: 'A filling vegan burrito with beans, rice and fresh vegetables.',
    meals: ['lunch', 'dinner'],
    diets: ['vegetarian', 'vegan', 'lactose-free'],
    times: ['quick', 'meal-prep'],
    budgets: ['low'],
    calories: 610,
    protein: 23,
    carbs: 94,
    fats: 18,
    prepMinutes: 9,
    cost: 'Low',
    ingredients: ['1 large whole-wheat wrap', '160 g black beans', '120 g cooked rice', '½ avocado', 'Salsa', 'Lettuce'],
    steps: ['Warm beans and rice.', 'Layer all ingredients in the wrap.', 'Fold tightly and toast briefly if desired.'],
    swaps: ['Add tofu or vegan protein strips.', 'Use less rice and more lettuce for fat loss.'],
    coachTip: 'Mash some beans before rolling to help the burrito hold together.',
  },
  {
    title: 'Red lentil bolognese',
    subtitle: 'A high-fiber plant-based pasta sauce designed for batch cooking.',
    meals: ['lunch', 'dinner'],
    diets: ['vegetarian', 'vegan', 'lactose-free'],
    times: ['standard', 'meal-prep'],
    budgets: ['low'],
    calories: 625,
    protein: 29,
    carbs: 104,
    fats: 10,
    prepMinutes: 30,
    cost: 'Low',
    ingredients: ['90 g dry pasta', '90 g red lentils', 'Tomato passata', 'Carrot', 'Onion', 'Garlic and herbs'],
    steps: ['Cook onion, carrot and garlic.', 'Add lentils, passata and water, then simmer.', 'Cook pasta and combine with the sauce.'],
    swaps: ['Use lentil pasta for extra protein.', 'Add mushrooms for more volume.'],
    coachTip: 'Red lentils cook directly in the sauce and create a naturally thick texture.',
  },
  {
    title: 'Seitan kebab plate',
    subtitle: 'A protein-dense vegan plate with spiced seitan, flatbread and salad.',
    meals: ['lunch', 'dinner', 'post-workout'],
    diets: ['vegetarian', 'vegan', 'lactose-free'],
    times: ['standard'],
    budgets: ['medium', 'flexible'],
    calories: 590,
    protein: 48,
    carbs: 69,
    fats: 13,
    prepMinutes: 18,
    cost: 'Medium',
    ingredients: ['180 g seitan', '1 flatbread', 'Tomato', 'Cucumber', 'Red cabbage', 'Tahini lemon sauce'],
    steps: ['Sear sliced seitan with kebab spices.', 'Chop the salad.', 'Serve with warm flatbread and tahini sauce.'],
    swaps: ['Use tofu or soy strips.', 'Serve over rice if flatbread is unavailable.'],
    coachTip: 'Seitan is very high in protein but should be paired with legumes over the day for amino-acid variety.',
  },
  {
    title: 'Mushroom bean risotto',
    subtitle: 'Creamy rice with mushrooms and white beans for extra plant protein.',
    meals: ['lunch', 'dinner'],
    diets: ['vegetarian', 'vegan', 'lactose-free'],
    times: ['standard', 'meal-prep'],
    budgets: ['low', 'medium'],
    calories: 565,
    protein: 22,
    carbs: 88,
    fats: 13,
    prepMinutes: 29,
    cost: 'Low',
    ingredients: ['85 g risotto rice', '150 g white beans', '200 g mushrooms', 'Vegetable stock', 'Onion', 'Nutritional yeast'],
    steps: ['Cook onion and mushrooms.', 'Add rice and gradually stir in stock.', 'Fold in beans and nutritional yeast.'],
    swaps: ['Add peas for more protein.', 'Use parmesan for a vegetarian version.'],
    coachTip: 'White beans make risotto creamier while increasing fiber and protein.',
  },
  {
    title: 'Vegetable egg fried rice',
    subtitle: 'A fast way to turn leftover rice into a balanced protein-rich meal.',
    meals: ['lunch', 'dinner', 'post-workout'],
    diets: ['balanced', 'vegetarian', 'lactose-free'],
    times: ['quick'],
    budgets: ['low'],
    calories: 545,
    protein: 28,
    carbs: 73,
    fats: 16,
    prepMinutes: 9,
    cost: 'Low',
    ingredients: ['220 g cold cooked rice', '3 eggs', '100 g peas', 'Carrot', 'Spring onion', 'Soy sauce'],
    steps: ['Scramble eggs and set aside.', 'Stir-fry rice and vegetables.', 'Return eggs, add soy sauce and toss.'],
    swaps: ['Add chicken, shrimp or tofu.', 'Use cauliflower rice for a lighter meal.'],
    coachTip: 'Cold rice fries better than freshly cooked rice because it contains less surface moisture.',
  },
  {
    title: 'Cottage cheese berry crunch',
    subtitle: 'A sweet high-protein snack requiring no cooking.',
    meals: ['snack', 'breakfast', 'post-workout'],
    diets: ['balanced', 'vegetarian'],
    times: ['quick'],
    budgets: ['low', 'medium'],
    calories: 345,
    protein: 32,
    carbs: 36,
    fats: 9,
    prepMinutes: 3,
    cost: 'Low',
    ingredients: ['220 g cottage cheese', '120 g berries', '20 g granola', 'Cinnamon', '1 tsp honey'],
    steps: ['Add cottage cheese to a bowl.', 'Top with berries and granola.', 'Finish with cinnamon and honey.'],
    swaps: ['Use lactose-free cottage cheese.', 'Replace granola with oats or crushed rice cakes.'],
    coachTip: 'Cottage cheese provides slow-digesting casein protein and works well as an evening snack.',
  },
  {
    title: 'Edamame crunch snack box',
    subtitle: 'A portable plant-based snack with protein, fiber and fresh crunch.',
    meals: ['snack', 'lunch'],
    diets: ['vegetarian', 'vegan', 'lactose-free'],
    times: ['quick', 'meal-prep'],
    budgets: ['low', 'medium'],
    calories: 360,
    protein: 24,
    carbs: 42,
    fats: 12,
    prepMinutes: 7,
    cost: 'Low',
    ingredients: ['180 g shelled edamame', 'Carrot sticks', 'Cucumber', '2 rice cakes', 'Soy sauce', 'Sesame seeds'],
    steps: ['Cook and cool the edamame.', 'Pack with chopped vegetables and rice cakes.', 'Add soy sauce separately.'],
    swaps: ['Replace rice cakes with fruit.', 'Add roasted chickpeas for more crunch.'],
    coachTip: 'Edamame is one of the most protein-dense whole plant foods.',
  },
  {
    title: 'Protein rice cake stack',
    subtitle: 'A fast sweet-and-salty snack with almost no preparation.',
    meals: ['snack', 'breakfast', 'post-workout'],
    diets: ['balanced', 'vegetarian'],
    times: ['quick'],
    budgets: ['low'],
    calories: 375,
    protein: 27,
    carbs: 49,
    fats: 9,
    prepMinutes: 4,
    cost: 'Low',
    ingredients: ['4 rice cakes', '150 g skyr', '1 banana', '15 g peanut butter', 'Cinnamon'],
    steps: ['Spread skyr over the rice cakes.', 'Top with banana slices.', 'Drizzle with peanut butter and cinnamon.'],
    swaps: ['Use soy yogurt and vegan protein powder.', 'Use berries for a lighter version.'],
    coachTip: 'This is easy to digest before training, especially when eaten 60–90 minutes beforehand.',
  },
  {
    title: 'Chocolate cherry recovery smoothie',
    subtitle: 'A refreshing recovery drink with protein, fruit and fast carbohydrates.',
    meals: ['post-workout', 'snack', 'breakfast'],
    diets: ['balanced', 'vegetarian', 'lactose-free'],
    times: ['quick'],
    budgets: ['medium', 'flexible'],
    calories: 465,
    protein: 38,
    carbs: 63,
    fats: 8,
    prepMinutes: 4,
    cost: 'Medium',
    ingredients: ['250 ml lactose-free milk', '30 g plant protein powder', '150 g frozen cherries', '1 banana', '1 tsp cocoa', 'Ice'],
    steps: ['Add all ingredients to a blender.', 'Blend until smooth.', 'Adjust thickness with water or ice.'],
    swaps: ['Use soy milk for a plant-based version.', 'Add oats for a higher-calorie recovery shake.'],
    coachTip: 'Frozen cherries provide flavor and carbohydrates without needing added sugar.',
  },
  {
    title: 'No-bake oat protein bites',
    subtitle: 'Small meal-prep bites for a practical pre-workout energy boost.',
    meals: ['snack', 'post-workout'],
    diets: ['balanced', 'vegetarian', 'vegan', 'lactose-free'],
    times: ['quick', 'meal-prep'],
    budgets: ['low'],
    calories: 320,
    protein: 20,
    carbs: 37,
    fats: 12,
    prepMinutes: 10,
    cost: 'Low',
    ingredients: ['50 g oats', '20 g plant protein powder', '20 g peanut butter', '20 g dates', 'Cinnamon', 'A little water'],
    steps: ['Blend or finely chop the dates.', 'Mix all ingredients into a firm dough.', 'Roll into bites and refrigerate.'],
    swaps: ['Use sunflower seed butter.', 'Add cocoa or coconut for a different flavor.'],
    coachTip: 'Keep portions measured because energy bites are compact and easy to overeat.',
  },
  {
    title: 'Hummus protein snack plate',
    subtitle: 'A balanced no-cook plate with hummus, eggs and vegetables.',
    meals: ['snack', 'lunch'],
    diets: ['balanced', 'vegetarian', 'lactose-free'],
    times: ['quick', 'meal-prep'],
    budgets: ['low', 'medium'],
    calories: 440,
    protein: 25,
    carbs: 43,
    fats: 20,
    prepMinutes: 6,
    cost: 'Low',
    ingredients: ['70 g hummus', '2 boiled eggs', 'Carrot', 'Cucumber', '1 small pita', 'Paprika'],
    steps: ['Slice the vegetables and eggs.', 'Add hummus to a small bowl.', 'Serve everything with pita and paprika.'],
    swaps: ['Use edamame instead of eggs for a vegan plate.', 'Use extra vegetables and half the pita for fat loss.'],
    coachTip: 'Boil several eggs in advance to make balanced snacks easier during the week.',
  },
  {
    title: 'High-protein cereal recovery bowl',
    subtitle: 'A very fast post-workout bowl when cooking is not practical.',
    meals: ['post-workout', 'breakfast', 'snack'],
    diets: ['balanced', 'vegetarian'],
    times: ['quick'],
    budgets: ['low', 'medium'],
    calories: 525,
    protein: 39,
    carbs: 78,
    fats: 8,
    prepMinutes: 3,
    cost: 'Low',
    ingredients: ['60 g whole-grain cereal', '300 ml high-protein milk', '150 g skyr', '1 banana', 'Cinnamon'],
    steps: ['Add cereal to a bowl.', 'Pour over milk.', 'Top with skyr, banana and cinnamon.'],
    swaps: ['Use soy milk and plant protein yogurt.', 'Replace banana with berries for fewer carbohydrates.'],
    coachTip: 'This gives rapid carbohydrates plus enough protein for recovery after a late session.',
  },
  {
    title: 'Avocado black bean tofu salad',
    subtitle: 'A high-fiber vegan lunch full of healthy fats and complete protein.',
    meals: ['lunch', 'dinner'],
    diets: ['vegan', 'vegetarian', 'lactose-free'],
    times: ['quick', 'meal-prep'],
    budgets: ['medium'],
    calories: 530,
    protein: 26,
    carbs: 45,
    fats: 25,
    prepMinutes: 10,
    cost: 'Medium',
    ingredients: ['150 g firm tofu', '100 g black beans', '½ avocado', 'Cherry tomatoes', 'Red onion', 'Lemon juice and cilantro'],
    steps: ['Cube tofu and dice avocado, tomatoes, and onion.', 'Rinse and drain black beans.', 'Toss all ingredients together with lemon juice, salt, and pepper.'],
    swaps: ['Use chickpeas instead of black beans.', 'Add corn for a bit of sweetness.'],
    coachTip: 'Let the salad sit for 10 minutes before eating to let the flavors blend.',
  },
  {
    title: 'Sweet potato salmon bites',
    subtitle: 'Roasted sweet potato cubes with baked salmon and a lemon dill dressing.',
    meals: ['lunch', 'dinner'],
    diets: ['balanced', 'lactose-free'],
    times: ['standard', 'meal-prep'],
    budgets: ['medium', 'flexible'],
    calories: 640,
    protein: 42,
    carbs: 58,
    fats: 22,
    prepMinutes: 25,
    cost: 'High',
    ingredients: ['150 g salmon fillet', '250 g sweet potatoes', 'Asparagus', '1 tsp olive oil', 'Lemon', 'Fresh dill'],
    steps: ['Dice sweet potatoes and roast with olive oil.', 'Cube the salmon and bake during the last 10 minutes.', 'Toss with steamed asparagus, dill, and lemon juice.'],
    swaps: ['Use white fish for lower fat and budget.', 'Swap asparagus for green beans.'],
    coachTip: 'Cubing the salmon makes it cook faster and absorb more flavor from the dressing.',
  },
  {
    title: 'Mexican spiced chicken fajita bowl',
    subtitle: 'Everything you love in fajitas, minus the wrap.',
    meals: ['lunch', 'dinner', 'post-workout'],
    diets: ['balanced', 'lactose-free'],
    times: ['standard', 'meal-prep'],
    budgets: ['low', 'medium'],
    calories: 595,
    protein: 51,
    carbs: 65,
    fats: 13,
    prepMinutes: 20,
    cost: 'Medium',
    ingredients: ['160 g chicken breast', '150 g cooked rice', 'Bell peppers', 'Onion', 'Jalapeno', 'Fajita seasoning'],
    steps: ['Slice chicken and vegetables into strips.', 'Cook chicken with fajita spices or taco seasoning.', 'Add vegetables until tender, then serve over rice.'],
    swaps: ['Use shrimp or lean steak.', 'Top with a dollop of Greek yogurt instead of sour cream.'],
    coachTip: 'Cooking the peppers slightly less keeps them crunchy and increases volume.',
  },
  {
    title: 'Matcha mango smoothie',
    subtitle: 'An antioxidant-rich smoothie with a natural caffeine boost.',
    meals: ['breakfast', 'snack'],
    diets: ['balanced', 'vegetarian', 'lactose-free', 'vegan'],
    times: ['quick'],
    budgets: ['medium'],
    calories: 360,
    protein: 21,
    carbs: 52,
    fats: 9,
    prepMinutes: 5,
    cost: 'Medium',
    ingredients: ['1 tsp matcha powder', '150 g frozen mango', '250 ml almond milk', '20 g plant protein powder', '10 g chia seeds'],
    steps: ['Sift the matcha powder to avoid clumps.', 'Add all ingredients into the blender.', 'Blend until creamy.'],
    swaps: ['Swap mango for pineapple or peach.', 'Use soy milk for more protein.'],
    coachTip: 'Matcha is great before a morning workout because it provides steady energy without the crash.',
  },
  {
    title: 'Veggie scramble English muffin',
    subtitle: 'A warm, satisfying breakfast sandwich to grab on the go.',
    meals: ['breakfast', 'snack'],
    diets: ['balanced', 'vegetarian'],
    times: ['quick'],
    budgets: ['low'],
    calories: 410,
    protein: 24,
    carbs: 40,
    fats: 15,
    prepMinutes: 10,
    cost: 'Low',
    ingredients: ['1 whole-wheat English muffin', '2 eggs', 'Spinach', 'Mushrooms', 'Slice of light cheese'],
    steps: ['Toast the English muffin.', 'Scramble eggs with diced mushrooms and spinach.', 'Assemble the sandwich with melted cheese.'],
    swaps: ['Use egg whites to save fats.', 'Add a slice of turkey or ham.'],
    coachTip: 'Make the scramble the night before and just warm it in the muffin for maximum speed.',
  },
  {
    title: 'Turkey meatballs with tzatziki',
    subtitle: 'Juicy baked meatballs dipped in a cool, creamy sauce.',
    meals: ['lunch', 'dinner'],
    diets: ['balanced'],
    times: ['standard', 'meal-prep'],
    budgets: ['low', 'medium'],
    calories: 550,
    protein: 48,
    carbs: 42,
    fats: 19,
    prepMinutes: 25,
    cost: 'Medium',
    ingredients: ['200 g turkey mince', 'Oregano and garlic', '50 g tzatziki', 'Cucumber and tomato salad', '50 g dry couscous'],
    steps: ['Mix turkey with herbs, roll into balls, and bake.', 'Prepare couscous with hot water.', 'Serve meatballs over couscous with salad and a dollop of tzatziki.'],
    swaps: ['Use chicken mince.', 'Replace couscous with a flatbread.'],
    coachTip: 'Tzatziki acts as both a dip and a dressing for the salad to keep meals flavorful.',
  },
  {
    title: 'Lemon white bean toast',
    subtitle: 'Crisp sourdough, creamy beans and a bright lemon finish.',
    meals: ['breakfast', 'lunch', 'snack'], diets: ['vegetarian', 'vegan', 'lactose-free'],
    times: ['quick'], budgets: ['low', 'medium'],
    calories: 445, protein: 22, carbs: 69, fats: 9, prepMinutes: 8, cost: 'Low',
    ingredients: ['180 g drained white beans', '2 slices sourdough bread (80 g)', '50 g baby spinach', '1 tsp olive oil', '½ lemon', 'Garlic and black pepper'],
    steps: ['Toast the bread. Drain and rinse the beans.', 'Warm the beans with oil, garlic and spinach, then mash lightly.', 'Spoon onto the toast and finish with lemon zest, juice and pepper.'],
    swaps: ['Use whole-grain bread for a firmer bite.', 'Replace spinach with rocket added just before serving.'],
    coachTip: 'Mash only half the beans so the topping stays creamy with a little texture.',
  },
  {
    title: 'Smoky chickpea couscous',
    subtitle: 'A warm pantry bowl with sweet peppers, parsley and smoked paprika.',
    meals: ['lunch', 'dinner', 'post-workout'], diets: ['vegetarian', 'vegan', 'lactose-free'],
    times: ['quick', 'meal-prep'], budgets: ['low', 'medium'],
    calories: 560, protein: 23, carbs: 89, fats: 12, prepMinutes: 8, cost: 'Low',
    ingredients: ['60 g dry couscous', '180 g drained chickpeas', '100 g jarred roasted peppers', '1 tsp olive oil', '½ lemon', 'Parsley and smoked paprika'],
    steps: ['Cover the couscous with boiling water according to the packet and leave for 5 minutes.', 'Warm the rinsed chickpeas with oil and smoked paprika.', 'Fluff the couscous and fold in chickpeas, sliced peppers, parsley and lemon juice.'],
    swaps: ['Use cooked quinoa instead of couscous.', 'Add chopped cucumber after cooling for a packed lunch.'],
    coachTip: 'Keep a jar of roasted peppers in the fridge for meals that need almost no chopping.',
  },
  {
    title: 'Ginger edamame soba',
    subtitle: 'Sesame noodles with edamame, crisp cucumber and a ginger-lime dressing.',
    meals: ['lunch', 'dinner', 'post-workout'], diets: ['vegetarian', 'vegan', 'lactose-free'],
    times: ['quick'], budgets: ['low', 'medium'],
    calories: 555, protein: 29, carbs: 76, fats: 15, prepMinutes: 10, cost: 'Low',
    ingredients: ['75 g dry soba noodles', '150 g shelled edamame', '100 g cucumber', '1 tsp sesame oil', '1 tsp sesame seeds', 'Soy sauce, grated ginger and lime'],
    steps: ['Boil the noodles following the packet, adding edamame for the final 3 minutes.', 'Drain and rinse briefly, then mix sesame oil, soy sauce, ginger and lime.', 'Toss with the dressing, sliced cucumber and sesame seeds.'],
    swaps: ['Use rice noodles if you prefer.', 'Replace cucumber with finely sliced carrots or cabbage.'],
    coachTip: 'Rinsing soba after cooking removes excess starch and keeps the noodles separate.',
  },
  {
    title: 'Miso tofu & broccoli tray',
    subtitle: 'Golden tofu and roasted broccoli with a savory miso glaze.',
    meals: ['lunch', 'dinner', 'post-workout'], diets: ['vegetarian', 'vegan', 'lactose-free'],
    times: ['standard', 'meal-prep'], budgets: ['medium', 'flexible'],
    calories: 635, protein: 35, carbs: 70, fats: 24, prepMinutes: 25, cost: 'Medium',
    ingredients: ['200 g firm tofu', '180 g cooked rice', '200 g broccoli', '1 tbsp miso paste', '1 tsp sesame oil', 'Lime, ginger and a little water'],
    steps: ['Heat the oven to 220°C. Pat the tofu dry and cut into cubes.', 'Mix miso, sesame oil, ginger and water. Coat the tofu and broccoli.', 'Roast on a lined tray for 20 minutes, turning halfway. Serve with hot rice and lime.'],
    swaps: ['Use green beans instead of broccoli.', 'Serve with cooked quinoa instead of rice.'],
    coachTip: 'Leave space between the tofu cubes on the tray so the edges turn golden.',
  },
  {
    title: 'Pear & cinnamon yogurt bowl',
    subtitle: 'Cool, creamy skyr with sweet pear, toasted oats and walnuts.',
    meals: ['breakfast', 'snack', 'post-workout'], diets: ['balanced', 'vegetarian'],
    times: ['quick'], budgets: ['low', 'medium'],
    calories: 420, protein: 32, carbs: 52, fats: 10, prepMinutes: 5, cost: 'Low',
    ingredients: ['250 g plain skyr', '1 pear', '35 g oats', '10 g walnuts', 'Cinnamon', 'Lemon zest'],
    steps: ['Spoon skyr into a bowl and slice the pear.', 'Toast the oats in a dry pan for 2 minutes, stirring.', 'Top with pear, oats, chopped walnuts, cinnamon and lemon zest.'],
    swaps: ['Use apple or fresh berries instead of pear.', 'Use lactose-free skyr when needed.'],
    coachTip: 'Let the toasted oats cool for a minute before adding them to keep the yogurt chilled.',
  },
  {
    title: 'Lemon ricotta & pea pasta',
    subtitle: 'A silky lemon sauce, sweet peas and plenty of fresh black pepper.',
    meals: ['lunch', 'dinner', 'post-workout'], diets: ['balanced', 'vegetarian'],
    times: ['standard'], budgets: ['low', 'medium'],
    calories: 645, protein: 30, carbs: 87, fats: 20, prepMinutes: 18, cost: 'Low',
    ingredients: ['90 g dry whole-wheat pasta', '100 g ricotta', '120 g frozen peas', '50 g spinach', '½ lemon', 'Black pepper and fresh basil'],
    steps: ['Cook the pasta, adding peas for the final 3 minutes. Reserve a mug of pasta water.', 'Stir ricotta with lemon zest, juice, pepper and a splash of pasta water.', 'Fold in pasta, peas and spinach over low heat. Finish with basil.'],
    swaps: ['Use cottage cheese blended smooth instead of ricotta.', 'Try broccoli florets instead of peas.'],
    coachTip: 'Add pasta water a spoonful at a time until the sauce lightly coats every piece.',
  },
  {
    title: 'Paprika chicken & bulgur',
    subtitle: 'Smoky chicken, fluffy bulgur and a crisp cucumber-tomato salad.',
    meals: ['lunch', 'dinner', 'post-workout'], diets: ['balanced', 'lactose-free'],
    times: ['standard', 'meal-prep'], budgets: ['low', 'medium'],
    calories: 590, protein: 48, carbs: 68, fats: 14, prepMinutes: 20, cost: 'Low',
    ingredients: ['170 g chicken breast', '75 g dry bulgur', '100 g cucumber', '100 g tomato', '2 tsp olive oil', 'Smoked paprika, lemon and parsley'],
    steps: ['Cook bulgur according to the packet. Dice the salad vegetables.', 'Slice chicken into strips, season with paprika and cook in the oil until fully cooked.', 'Serve chicken over bulgur with the salad, parsley and lemon juice.'],
    swaps: ['Use turkey breast instead of chicken.', 'Replace bulgur with cooked brown rice.'],
    coachTip: 'Store the salad separately when prepping portions to keep the vegetables crisp.',
  },
  {
    title: 'Turkey & lentil lettuce cups',
    subtitle: 'Fresh, crunchy cups with lentils, cooked turkey and a mustard dressing.',
    meals: ['lunch', 'dinner', 'snack', 'post-workout'], diets: ['balanced', 'lactose-free'],
    times: ['quick'], budgets: ['low', 'medium'],
    calories: 470, protein: 43, carbs: 46, fats: 12, prepMinutes: 10, cost: 'Low',
    ingredients: ['120 g cooked turkey breast', '150 g cooked lentils', '1 small whole-wheat pita (40 g)', '4 large lettuce leaves', '100 g carrot and cucumber', '1 tsp olive oil, mustard and lemon'],
    steps: ['Rinse and dry the lettuce. Shred the cooked turkey and dice the vegetables.', 'Whisk oil, mustard and lemon, then toss with the turkey, lentils and vegetables.', 'Spoon into lettuce leaves and serve with warm pita.'],
    swaps: ['Use cooked chicken leftovers.', 'Use chopped firm tofu instead of turkey for a plant-based variation.'],
    coachTip: 'Choose the sturdy outer lettuce leaves and fill them just before eating.',
  }

];

// Goal preferences rank complete recipes; nutrition stays tied to the listed serving.
const GOAL_TIPS: Record<NutritionGoal, string> = {
  lose: 'For a lighter meal, keep the protein serving and add extra vegetables.',
  maintain: 'The listed ingredients make one serving.',
  gain: 'For a larger meal, add a side of rice, bread or fruit to suit your appetite.',
};

export function createMealRecommendation(answers: AssistantAnswers): MealRecommendation {
  const compatibleMeals = MEALS.filter(meal =>
    meal.meals.includes(answers.meal) && isDietCompatible(meal, answers.diet),
  );
  const timeMatches = compatibleMeals.filter(meal =>
    answers.time === 'meal-prep' ? meal.times.includes('meal-prep') :
      meal.prepMinutes <= (answers.time === 'quick' ? 10 : 30),
  );
  const budgetMatches = timeMatches.filter(meal =>
    answers.budget === 'flexible' || meal.cost === 'Low' ||
      (answers.budget === 'medium' && meal.cost === 'Medium'),
  );
  // All current preference combinations have a match. Keep a diet-safe fallback
  // for future catalog additions, with the actual time and cost still displayed.
  const candidates = budgetMatches.length ? budgetMatches : timeMatches.length ? timeMatches : compatibleMeals;
  const scoredMeals = candidates.map(meal => {
    let score = 0;
    if (answers.goal === 'gain' && meal.protein >= 30) score += 2;
    if (answers.goal === 'gain' && meal.calories >= 500) score += 1;
    if (answers.goal === 'lose' && meal.calories <= 520) score += 2;
    if (answers.goal === 'lose' && meal.protein >= 25) score += 1;
    return { meal, score };
  }).sort((first, second) => second.score - first.score);

  const topScore = scoredMeals[0].score;
  const closeMatches = scoredMeals.filter(candidate => candidate.score >= topScore - 2);
  const answerKey = `${answers.goal}-${answers.meal}-${answers.diet}-${answers.time}-${answers.budget}`;
  const selected = closeMatches[getNextRecommendationIndex(answerKey, closeMatches.length)].meal;

  return {
    title: selected.title,
    subtitle: selected.subtitle,
    calories: selected.calories,
    protein: selected.protein,
    carbs: selected.carbs,
    fats: selected.fats,
    prepMinutes: selected.prepMinutes,
    cost: selected.cost,
    ingredients: [...selected.ingredients],
    steps: [...selected.steps],
    swaps: [...selected.swaps],
    coachTip: `${GOAL_TIPS[answers.goal]} ${selected.coachTip}`,
  };
}

function isDietCompatible(meal: MealTemplate, diet: DietType): boolean {
  return diet === 'balanced' || meal.diets.includes(diet) ||
    (diet === 'vegetarian' && meal.diets.includes('vegan'));
}

const recommendationIndexes = new Map<string, number>();

function getNextRecommendationIndex(answerKey: string, resultCount: number): number {
  const currentIndex = recommendationIndexes.get(answerKey) ?? 0;
  recommendationIndexes.set(answerKey, (currentIndex + 1) % resultCount);
  return currentIndex % resultCount;
}
